"""
Manual industry overrides for companies that couldn't be classified by keyword rules.
Dry-run by default; --apply to write.
"""
import os, sys
PROD_DSN = 'postgresql://postgres:gnhrxOkYHTPaEIYuetmcXptfkTcvnLPp@switchyard.proxy.rlwy.net:48202/railway'
os.environ.setdefault('DATABASE_URL', PROD_DSN)
from app import create_app
from app.models import Company, db

APPLY = '--apply' in sys.argv

# name (exact) → canonical industry
OVERRIDES = {
    # ── E-commerce & Retail ──────────────────────────────────────────────────
    '10Beauty': 'E-commerce & Retail',
    '1-800 Contacts': 'E-commerce & Retail',
    '3 Day Blinds (Sales)': 'E-commerce & Retail',
    'AG1': 'E-commerce & Retail',
    'air up': 'E-commerce & Retail',
    'Allbirds Retail': 'E-commerce & Retail',
    'ALO': 'E-commerce & Retail',
    'ALOHA Collection Inc.': 'E-commerce & Retail',
    'ANINE BING': 'E-commerce & Retail',
    'Authentic Brands Group': 'E-commerce & Retail',
    'AutoDS': 'E-commerce & Retail',
    'Aviator Nation': 'E-commerce & Retail',
    'Babylist': 'E-commerce & Retail',
    'Banza': 'E-commerce & Retail',
    'BaubleBar': 'E-commerce & Retail',
    'Bauer Hockey/ Cascade Maverik Lacrosse': 'E-commerce & Retail',
    'BELLA+CANVAS': 'E-commerce & Retail',
    'Bellroy': 'E-commerce & Retail',
    'Beyond': 'E-commerce & Retail',
    'Bobbie': 'E-commerce & Retail',
    'Bold Metrics': 'E-commerce & Retail',
    'Bombas': 'E-commerce & Retail',
    'BRKZ': 'E-commerce & Retail',
    'Brooklinen': 'E-commerce & Retail',
    'BRUNT Workwear': 'E-commerce & Retail',
    'B-Stock': 'E-commerce & Retail',
    'Bubble Skincare': 'E-commerce & Retail',
    'Butternut Box': 'E-commerce & Retail',
    'Daiya Foods Inc.': 'E-commerce & Retail',
    'Decathlon Digital FR': 'E-commerce & Retail',
    'Dr. Squatch': 'E-commerce & Retail',
    'Empower Brands': 'E-commerce & Retail',
    'Ernesta': 'E-commerce & Retail',
    'Everlane': 'E-commerce & Retail',
    'Filson': 'E-commerce & Retail',
    'Flip App': 'E-commerce & Retail',
    'Flip': 'E-commerce & Retail',
    'Flip GmbH': 'E-commerce & Retail',
    'Flipp': 'E-commerce & Retail',
    'Fresh Prints': 'E-commerce & Retail',
    'Grön Confections': 'E-commerce & Retail',
    'JD Sports': 'E-commerce & Retail',
    'Jenni Kayne': 'E-commerce & Retail',
    'KEEN Footwear': 'E-commerce & Retail',
    'KHAITE': 'E-commerce & Retail',
    'KIND Snacks': 'E-commerce & Retail',
    'KLARSTEIN': 'E-commerce & Retail',
    'La Senza': 'E-commerce & Retail',
    'Little Spoon': 'E-commerce & Retail',
    'Lola Blankets': 'E-commerce & Retail',
    'Lucky Beverage Co': 'E-commerce & Retail',
    'Lush Handmade Cosmetics': 'E-commerce & Retail',
    'Madison Reed': 'E-commerce & Retail',
    'MANSCAPED': 'E-commerce & Retail',
    'Mejuri': 'E-commerce & Retail',
    'Mishimoto': 'E-commerce & Retail',
    'Mizzen+Main': 'E-commerce & Retail',
    'Paula\'s Choice Skincare': 'E-commerce & Retail',
    'Perry Ellis International': 'E-commerce & Retail',
    'Quince': 'E-commerce & Retail',
    'Reformation': 'E-commerce & Retail',
    'rhode skin': 'E-commerce & Retail',
    'Rothy\'s': 'E-commerce & Retail',
    'Ruggable': 'E-commerce & Retail',
    'SanMar- External': 'E-commerce & Retail',
    'Scotch': 'E-commerce & Retail',
    'Tecovas': 'E-commerce & Retail',
    'THE ICONIC': 'E-commerce & Retail',
    'The Honest Company': 'E-commerce & Retail',
    'Thrive Market': 'E-commerce & Retail',
    'True Classic': 'E-commerce & Retail',
    'Uncommon Goods': 'E-commerce & Retail',
    'Van Leeuwen Ice Cream': 'E-commerce & Retail',
    'Alt': 'E-commerce & Retail',
    'Anchanto': 'E-commerce & Retail',
    'Beatbox Beverages, LLC': 'E-commerce & Retail',
    'Double Good': 'E-commerce & Retail',
    'Emota': 'E-commerce & Retail',
    'Fetch': 'E-commerce & Retail',
    'fairlife': 'E-commerce & Retail',
    'Weedmaps': 'E-commerce & Retail',
    'Weee! Inc': 'E-commerce & Retail',
    'Who Gives A Crap': 'E-commerce & Retail',
    'Wallapop': 'E-commerce & Retail',
    'Unreal Snacks': 'E-commerce & Retail',
    'Vital Farms': 'E-commerce & Retail',

    # ── Fintech ──────────────────────────────────────────────────────────────
    '12twenty': 'HR Tech',  # actually HR Tech (early career recruiting)
    'AgWest Farm Credit': 'Fintech',
    'Agilize': 'Fintech',
    'Akoya': 'Fintech',
    'Akuna Capital': 'Fintech',
    'Alpaca': 'Fintech',
    'Alpha Alternatives': 'Fintech',
    'AlphaSense': 'Data & Analytics',
    'Alumni Ventures': 'Fintech',
    'American Capital Group': 'Fintech',
    'Ansa': 'Fintech',
    'Appstar': 'Fintech',
    'Aquatic Capital Management': 'Fintech',
    'Array': 'Fintech',
    'Ascend': 'Fintech',
    'Ascend Partner Firms': 'Fintech',
    'Assessoria de Investimentos - XP Inc.': 'Fintech',
    'Assured Guaranty': 'Fintech',
    'Assured Guaranty Opportunistic': 'Fintech',
    'ATLAS SP': 'Fintech',
    'Audax Group': 'Fintech',
    'AvidXchange, Inc.': 'Fintech',
    'Axi': 'Fintech',
    'Axial': 'Fintech',
    'B2C2': 'Fintech',
    'Backbase': 'Fintech',
    'Bain Capital Ventures': 'Fintech',
    'Banco PAN': 'Fintech',
    'Baron Capital': 'Fintech',
    'Baubap': 'Fintech',
    'BBPOS Limited': 'Fintech',
    'BCB Group': 'Fintech',
    'Belltower Fund Group': 'Fintech',
    'Bertram Capital Management': 'Fintech',
    'Bessemer Venture Partners': 'Fintech',
    'Better Debt Solutions': 'Fintech',
    'BILL': 'Fintech',
    'Billtrust India Careers': 'Fintech',
    'Billtrust US Careers': 'Fintech',
    'Birch Hill Equity Partners': 'Fintech',
    'Bitpanda': 'Fintech',
    'Bitso': 'Fintech',
    'BlueCrest Capital Management': 'Fintech',
    'Bottomline': 'Fintech',
    'Bracebridge Capital': 'Fintech',
    'Branch': 'Fintech',
    'B. Riley Securities': 'Fintech',
    'Broadway Ventures': 'Fintech',
    'BTG Pactual Chile': 'Fintech',
    'BTG Pactual LA': 'Fintech',
    'BTIG': 'Fintech',
    'CAIS': 'Fintech',
    'Careers at Tide': 'Fintech',
    'Current': 'Fintech',
    'Dalio Family Office': 'Fintech',
    'Davidson Kempner Capital Management': 'Fintech',
    'Dodgshun Medlin': 'Fintech',
    'DRW': 'Fintech',
    'DRW Montreal': 'Fintech',
    'Ducera Partners - Experienced Hires': 'Fintech',
    'Eagle Business Credit': 'Fintech',
    'Earnest': 'Fintech',
    'EarnIn': 'Fintech',
    'EBANX': 'Fintech',
    'Ebury': 'Fintech',
    'eLEND': 'Fintech',
    'Elwood Technologies': 'Fintech',
    'Episode Six': 'Fintech',
    'Ethic': 'Fintech',
    'Exactera': 'Fintech',
    'ExodusPoint': 'Fintech',
    'Exodus Movement Inc.': 'Fintech',
    'Anthos Family Office': 'Fintech',
    'Farther': 'Fintech',
    'Feedzai': 'Fintech',
    'FFG FINANZCHECK Finanzportale GmbH': 'Fintech',
    'FIS® Amount™': 'Fintech',
    'Flipside': 'Fintech',
    'Flow Traders': 'Fintech',
    'Focus Partners Australia & Escala Partners': 'Fintech',
    'Focus Partners Wealth': 'Fintech',
    'Forge Global': 'Fintech',
    'Form3 - External': 'Fintech',
    'Forter': 'Fintech',
    'Garda Capital Partners': 'Fintech',
    'GCM Grosvenor': 'Fintech',
    'Gelfand, Rennert & Feldman, Focus Partners Business Management': 'Fintech',
    'Geneva Trading': 'Fintech',
    'Intermex Wire Transfer': 'Fintech',
    'Juno': 'Fintech',
    'Kadmos': 'Fintech',
    'Kalshi': 'Fintech',
    'Kapitus': 'Fintech',
    'Kard Financial, Inc.': 'Fintech',
    'Karbon': 'Fintech',
    'Kikoff': 'Fintech',
    'Kiavi': 'Fintech',
    'Knab': 'Fintech',
    'Koalafi': 'Fintech',
    'Kronos Research': 'Fintech',
    'Ladder': 'Fintech',
    'Ledgy': 'Fintech',
    'LendingTree': 'Fintech',
    'Lendz Financial': 'Fintech',
    'Leveris': 'Fintech',
    'Liberis': 'Fintech',
    'LionTree': 'Fintech',
    'LLR Partners': 'Fintech',
    'Long Ridge Equity Partners': 'Fintech',
    'Lucanet Group': 'Fintech',
    'Majority': 'Fintech',
    'MarketAxess': 'Fintech',
    'Marshall Wace': 'Fintech',
    'Massar Capital': 'Fintech',
    'MCO': 'Fintech',
    'Melio': 'Fintech',
    'MEMX': 'Fintech',
    'Mercer Advisors': 'Fintech',
    'Metronome': 'Fintech',
    'MIO Partners': 'Fintech',
    'Mission Lane': 'Fintech',
    'Mission Lane LLC': 'Fintech',
    'Modera Wealth Management': 'Fintech',
    'Moneyherogroup': 'Fintech',
    'Momentum Financial Services Group': 'Fintech',
    'Numeral': 'Fintech',
    'Pagaya': 'Fintech',
    'Pagaya Israel': 'Fintech',
    'Paidy Inc/Paidy合同会社': 'Fintech',
    'Pangea Money Transfer': 'Fintech',
    'Pathward, N.A.': 'Fintech',
    'PawaPay': 'Fintech',
    'PayDo': 'Fintech',
    'Payhawk': 'Fintech',
    'PayHawk': 'Fintech',
    'PayIt': 'Fintech',
    'PayPay Card': 'Fintech',
    'PayPay Securities': 'Fintech',
    'PDT Partners': 'Fintech',
    'PhonePe': 'Fintech',
    'Pilot.com': 'Fintech',
    'Pinwheel': 'Fintech',
    'PINE Advisor Solutions': 'Fintech',
    'Plata Card': 'Fintech',
    'Plooto': 'Fintech',
    'Point72': 'Fintech',
    'Polychain Capital': 'Fintech',
    'Prospa': 'Fintech',
    'ProShares': 'Fintech',
    'PsiQuantum': 'Fintech',  # quantum computing for finance
    'Public': 'Fintech',
    'Pulley': 'Fintech',
    'Pump.co': 'Fintech',
    'Pzena Investment Management': 'Fintech',
    'Qube Research & Technologies': 'Fintech',
    'Quadrature Capital': 'Fintech',
    'Raisin': 'Fintech',
    'Ramp Network': 'Fintech',
    'Razorpay Software Private Limited': 'Fintech',
    'Reach Financial': 'Fintech',
    'Relay': 'Fintech',
    'Ripple': 'Fintech',
    'Riskified': 'Fintech',
    'Rocket Money': 'Fintech',
    'RootstockLabs Ltd.': 'Fintech',
    'Rothesay': 'Fintech',
    'RQD * Clearing LLC': 'Fintech',
    'Samlino': 'Fintech',
    'SBI Growth': 'Fintech',
    'Schonfeld': 'Fintech',
    'SCS Financial': 'Fintech',
    'Seatown': 'Fintech',
    'Selini Capital': 'Fintech',
    'Soros Fund Management': 'Fintech',
    'Stevens Capital Management LP': 'Fintech',
    'tastylive': 'Fintech',
    'tastytrade': 'Fintech',
    'TaxValet': 'Fintech',
    'ThinkMarkets': 'Fintech',
    'Thunes': 'Fintech',
    'TIFIN': 'Fintech',
    'Tipalti': 'Fintech',
    'Toast': 'Fintech',
    'Topstep': 'Fintech',
    'Tower Research Capital': 'Fintech',
    'Trade Republic': 'Fintech',
    'TransferGo': 'Fintech',
    'Treasury Prime': 'Fintech',
    'Trumid': 'Fintech',
    'Trust & Will': 'Fintech',
    'Tudor Investment Corporation': 'Fintech',
    'Upstart': 'Fintech',
    'Upgrade': 'Fintech',
    'VantageScore': 'Fintech',
    'Varicent': 'Fintech',
    'Vatic Labs': 'Fintech',
    'Vestmark, Inc.': 'Fintech',
    'Vestwell': 'Fintech',
    'Viking Global Investors': 'Fintech',
    'Vise': 'Fintech',
    'Virtu Financial': 'Fintech',
    'Vitta': 'Fintech',
    'Wall Street Prep': 'Fintech',
    'Wave': 'Fintech',
    'Weave': 'Fintech',
    'Winton': 'Fintech',
    'Wisetack': 'Fintech',
    'WorldQuant': 'Fintech',
    'XP Inc.': 'Fintech',
    'XTX Markets': 'Fintech',
    'Yale Investments': 'Fintech',
    'YipitData': 'Fintech',
    'YipitData (Alternative)': 'Fintech',

    # ── HealthTech ───────────────────────────────────────────────────────────
    'AffirmedRx, PBC': 'HealthTech',
    'Age Bold': 'HealthTech',
    'AirSculpt': 'HealthTech',
    'Alma': 'HealthTech',
    'Amwell': 'HealthTech',
    'ATI Advisory': 'HealthTech',
    'audibene / hear.com': 'HealthTech',
    'BillionToOne': 'HealthTech',
    'Biofourmis': 'HealthTech',
    'Bond Vet': 'HealthTech',
    'Boulder Care': 'HealthTech',
    'Cadwell': 'HealthTech',
    'Cortica - Neurodevelopmental': 'HealthTech',
    'Curaleaf': 'HealthTech',
    'Curative': 'HealthTech',
    'Datavant': 'HealthTech',
    'Dexis': 'HealthTech',
    'Dimagi': 'HealthTech',
    'Doctolib': 'HealthTech',
    'Doctors Without Borders / Médecins Sans Frontières (MSF) Canada': 'HealthTech',
    'Doctolib': 'HealthTech',
    'DSP-Eclipsys': 'HealthTech',
    'Dutchie': 'HealthTech',
    'Eliot Community Human Services': 'HealthTech',
    'Engage Senior Therapy': 'HealthTech',
    'Evergreen Nephrology': 'HealthTech',
    'Every Cure': 'HealthTech',
    'FSAStore.com': 'HealthTech',
    'InsightRX': 'HealthTech',
    'Inspiren': 'HealthTech',
    'Integrity Rehab Group': 'HealthTech',
    'Interwell Health': 'HealthTech',
    'IVX Health': 'HealthTech',
    'Kalderos': 'HealthTech',
    'Kaléo': 'HealthTech',
    'K Health': 'HealthTech',
    'League Inc.': 'HealthTech',
    'Lenus': 'HealthTech',
    'LightForce Orthodontics': 'HealthTech',
    'Life Link III': 'HealthTech',
    'Medecins Sans Frontieres (Doctors Without Borders) - Field': 'HealthTech',
    'MedElite Group, LLC.': 'HealthTech',
    'Médicos Sin Fronteras en México A.C [Proyectos en México y Centroamérica]': 'HealthTech',
    'Médicos Sin Fronteras en México A.C [Proyectos internacionales]': 'HealthTech',
    'MediSpend': 'HealthTech',
    'Medsien': 'HealthTech',
    'MCG Health': 'HealthTech',
    'Modern Animal': 'HealthTech',
    'Paragonix Technologies, Inc': 'HealthTech',
    'PathAI': 'HealthTech',
    'PerfectServe': 'HealthTech',
    'Personalis, Inc': 'HealthTech',
    'Practice Better': 'HealthTech',
    'Prenuvo': 'HealthTech',
    'Providence Digital Innovation Group': 'HealthTech',
    'Q-Centrix': 'HealthTech',
    'QGenda': 'HealthTech',
    'Rivia Mind': 'HealthTech',
    'Rivia Mind - Mental Healthcare': 'HealthTech',
    'Ro': 'HealthTech',
    'Roo': 'HealthTech',
    'RVO Health': 'HealthTech',
    'RVO Health Freelance Network': 'HealthTech',
    'RxSense': 'HealthTech',
    'RxVantage': 'HealthTech',
    'R-Zero': 'HealthTech',
    'Target RWE': 'HealthTech',
    'Tebra': 'HealthTech',
    'TeleTracking Technologies, Inc.': 'HealthTech',
    'The Michael J. Fox Foundation for Parkinson\'s Research': 'HealthTech',
    'The Oncology Institute of Hope and Innovation': 'HealthTech',
    'The Vascular Care Group': 'HealthTech',
    'Theoria Medical': 'HealthTech',
    'Thyme Care': 'HealthTech',
    'Two Chairs': 'HealthTech',
    'UK-Med': 'HealthTech',
    'Universal DX': 'HealthTech',
    'Unchained Labs': 'HealthTech',
    'Vail Health Hospital': 'HealthTech',
    'Valo Health': 'HealthTech',
    'Vanna Health': 'HealthTech',
    'VetEvolve': 'HealthTech',
    'Vicarious Surgical': 'HealthTech',
    'Vim': 'HealthTech',
    'Vitable Health': 'HealthTech',
    'Vita Health': 'HealthTech',
    'Vivodyne': 'HealthTech',
    'Waltz Health': 'HealthTech',
    'WelbeHealth': 'HealthTech',
    'Wellthy Care Network': 'HealthTech',
    'WellPower - All Jobs': 'HealthTech',
    'WellPower - Residential': 'HealthTech',

    # ── Gaming ───────────────────────────────────────────────────────────────
    '31st Union': 'Gaming',
    '5minlab': 'Gaming',
    'Bluehole Inc.': 'Gaming',
    'Bonfire Studios': 'Gaming',
    'Delasport': 'Gaming',
    'Digital Extremes': 'Gaming',
    'Easygo': 'Gaming',
    'FanDuel': 'Gaming',
    'Firaxis': 'Gaming',
    'Fortis Games': 'Gaming',
    'Insomniac Games': 'Gaming',
    'inZOI Studio': 'Gaming',
    'Jackpot': 'Gaming',
    'Jam Filled': 'Gaming',
    'Kambi': 'Gaming',
    'Kaizen Gaming': 'Gaming',
    'Kano': 'Gaming',
    'MobilityWare': 'Gaming',
    'Momentic Studios': 'Gaming',
    'Naughty Dog': 'Gaming',
    'Penn Interactive': 'Gaming',
    'PlayQ': 'Gaming',
    'PlayStation Waterloo Co-Op': 'Gaming',
    'PrizePicks': 'Gaming',
    'PUBG Madison': 'Gaming',
    'PUBG Studios': 'Gaming',
    'Rush Street Interactive': 'Gaming',
    'Rushdown Studios': 'Gaming',
    'Scopely': 'Gaming',
    'Sleeper': 'Gaming',
    'Tripwire Interactive': 'Gaming',
    'Turtle Rock Studios': 'Gaming',
    'Undead Labs': 'Gaming',
    'Underdog': 'Gaming',
    'Unknown Worlds': 'Gaming',
    'Visual Concepts': 'Gaming',
    'VGW': 'Gaming',
    'Wargaming': 'Gaming',
    'Wildlife Studios': 'Gaming',
    'WMS Industries': 'Gaming',
    'Wooga': 'Gaming',
    'Betsson Group': 'Gaming',
    'Betting Hero': 'Gaming',
    'Delasport': 'Gaming',
    'Dynamite Games': 'Gaming',
    'Evoplay Games': 'Gaming',
    'Flyway Games': 'Gaming',
    'GameTime United': 'Gaming',
    'Keen Software House': 'Gaming',
    'LeagueApps': 'Gaming',
    'LiveScore Group': 'Gaming',
    'Polyphony Digital': 'Gaming',
    'teamLFG': 'Gaming',

    # ── Marketing Tech ───────────────────────────────────────────────────────
    'AKQA': 'Marketing Tech',
    'Affinitiv': 'Marketing Tech',
    'AltiSales': 'Marketing Tech',
    'Appier': 'Marketing Tech',
    'ApotheCom': 'Marketing Tech',
    'Article Group': 'Marketing Tech',
    'AWeber': 'Marketing Tech',
    'Awin': 'Marketing Tech',
    'Axicom': 'Marketing Tech',
    'Barbarian': 'Marketing Tech',
    'Barkley': 'Marketing Tech',
    'BDA': 'Marketing Tech',
    'BerlinRosen': 'Marketing Tech',
    'Blip Global': 'Marketing Tech',
    'Blockgraph': 'Marketing Tech',
    'Blue Current': 'Marketing Tech',
    'BlueConic': 'Marketing Tech',
    'Blue State': 'Marketing Tech',
    'BluShark Digital': 'Marketing Tech',
    'BPD': 'Marketing Tech',
    'Brainlabs': 'Marketing Tech',
    'Branch Metrics': 'Marketing Tech',
    'Brandtech+': 'Marketing Tech',
    'Brandwatch': 'Marketing Tech',
    'Broadsign Careers': 'Marketing Tech',
    'Brunswick Group': 'Marketing Tech',
    'Burson': 'Marketing Tech',
    'C.A. Fortune': 'Marketing Tech',
    'Callrail': 'Marketing Tech',
    'CG Life': 'Marketing Tech',
    'Circa - IPG DXTRA': 'Marketing Tech',
    'DemandScience': 'Marketing Tech',
    'DEPT®': 'Marketing Tech',
    'Derris': 'Marketing Tech',
    'DeepIntent': 'Marketing Tech',
    'DoubleVerify': 'Marketing Tech',
    'EDO': 'Marketing Tech',
    'Emplifi (external posting)': 'Marketing Tech',
    'Emplifi FR': 'Marketing Tech',
    'FCB': 'Marketing Tech',
    'FGS Global': 'Marketing Tech',
    'FleishmanHillard': 'Marketing Tech',
    'Flywheel Digital': 'Marketing Tech',
    'Fospha': 'Marketing Tech',
    'Gallery Media Group': 'Marketing Tech',
    'Kepler Group': 'Marketing Tech',
    'Ketchumuscareers': 'Marketing Tech',
    'Known': 'Marketing Tech',
    'Kunai': 'Marketing Tech',
    'LTK UK': 'Marketing Tech',
    'Madison Logic': 'Marketing Tech',
    'Mammoth Growth': 'Marketing Tech',
    'maslansky + partners': 'Marketing Tech',
    'M Booth': 'Marketing Tech',
    'McKinney': 'Marketing Tech',
    'MiQ Digital': 'Marketing Tech',
    'MNTN': 'Marketing Tech',
    'Monks': 'Marketing Tech',
    'Pacvue': 'Marketing Tech',
    'PebblePost': 'Marketing Tech',
    'Perion Network Ltd': 'Marketing Tech',
    'Pixability': 'Marketing Tech',
    'PMG': 'Marketing Tech',
    'PMG UK': 'Marketing Tech',
    'Porter Novelli': 'Marketing Tech',
    'Power Digital': 'Marketing Tech',
    'PubMatic': 'Marketing Tech',
    'RAPP': 'Marketing Tech',
    'RD Station': 'Marketing Tech',
    'RD Station - Sourcing': 'Marketing Tech',
    'Reachdesk Ltd': 'Marketing Tech',
    'Reach3 Insights': 'Marketing Tech',
    'Red Ventures': 'Marketing Tech',
    'Reunion Marketing': 'Marketing Tech',
    'RTB House': 'Marketing Tech',
    'Scangroup': 'Marketing Tech',
    'Scorpion Enterprises, LLC': 'Marketing Tech',
    'TBWA\\Chiat\\Day': 'Marketing Tech',
    'Teads': 'Marketing Tech',
    'Thesis': 'Marketing Tech',
    'The Brand Agency': 'Marketing Tech',
    'TopCompare': 'Marketing Tech',
    'Topsort': 'Marketing Tech',
    'TripleLift': 'Marketing Tech',
    'Triple Whale': 'Marketing Tech',
    'TubeScience': 'Marketing Tech',
    'UserGems': 'Marketing Tech',
    'Viant Technology': 'Marketing Tech',
    'Viral Nation Inc.': 'Marketing Tech',
    'VML': 'Marketing Tech',
    'VOX Global': 'Marketing Tech',
    'VSA Partners': 'Marketing Tech',
    'Walker Sands': 'Marketing Tech',
    'Whalar Group': 'Marketing Tech',
    'WongDoody': 'Marketing Tech',
    'WPP': 'Marketing Tech',
    'WPP Media': 'Marketing Tech',
    'Wunderkind': 'Marketing Tech',
    'iSpot': 'Marketing Tech',
    'Invoca': 'Marketing Tech',

    # ── Developer Tools ──────────────────────────────────────────────────────
    '3Cloud': 'Developer Tools',
    'Affinidi': 'Developer Tools',
    'Airtame': 'Developer Tools',
    'AirTrunk': 'Developer Tools',
    'Algolia': 'Developer Tools',
    'Align Communications': 'Developer Tools',
    'Aligned': 'Developer Tools',
    'Amdaris': 'Developer Tools',
    'Amity': 'Developer Tools',
    'AnyDesk': 'Developer Tools',
    'apiphani': 'Developer Tools',
    'AppDirect': 'Developer Tools',
    'Appnovation Technologies': 'Developer Tools',
    'AppViewX': 'Developer Tools',
    'Aptitude 8': 'Developer Tools',
    'ArcTouch': 'Developer Tools',
    'Arionkoder': 'Developer Tools',
    'Arke': 'Developer Tools',
    'arsys EN': 'Developer Tools',
    'AssureSoft - Careers': 'Developer Tools',
    'Augment Code': 'Developer Tools',
    'Automattic Careers': 'Developer Tools',
    'Auvik Networks': 'Developer Tools',
    'Aviatrix': 'Developer Tools',
    'B12': 'Developer Tools',
    'Bandwidth': 'Developer Tools',
    'Baselayer': 'Developer Tools',
    'Beacon Software': 'Developer Tools',
    'Blueprint Technologies': 'Developer Tools',
    'Boingo': 'Developer Tools',
    'Boomi': 'Developer Tools',
    'Brave': 'Developer Tools',
    'Builder.io': 'Developer Tools',
    'Callibrity': 'Developer Tools',
    'Cutover': 'Developer Tools',
    'Cypress.io': 'Developer Tools',
    'DAS42': 'Data & Analytics',
    'DBeaver': 'Developer Tools',
    'Dedicated IT': 'Developer Tools',
    'Development Seed': 'Developer Tools',
    'DKB Code Factory': 'Developer Tools',
    'DNA': 'Developer Tools',
    'DoiT': 'Developer Tools',
    'Domino Data Lab': 'Data & Analytics',
    'DYOPATH': 'Developer Tools',
    'EdgeConneX': 'Developer Tools',
    'Effectual': 'Developer Tools',
    'Element Critical': 'Developer Tools',
    'Embrace': 'Developer Tools',
    'emnify': 'Developer Tools',
    'Encora': 'Developer Tools',
    'Ensono': 'Developer Tools',
    'ePlus Technology, inc.': 'Developer Tools',
    'Equal Experts': 'Developer Tools',
    'Eridan': 'Developer Tools',
    'Evergreen Services Group': 'Developer Tools',
    'Evio': 'Developer Tools',
    'Extenteamcareers': 'Developer Tools',
    'Extenteam Client Roles': 'Developer Tools',
    'eyeo': 'Developer Tools',
    'Files.com': 'Developer Tools',
    'Forward Networks': 'Developer Tools',
    'FOSSA': 'Developer Tools',
    'IP Fabric': 'Developer Tools',
    'Kentik': 'Developer Tools',
    'Knit': 'Developer Tools',
    'Launchpad Technologies': 'Developer Tools',
    'Linear': 'Developer Tools',
    'Liquid Instruments': 'Developer Tools',
    'Lokalise': 'Developer Tools',
    'Lucid Software': 'Developer Tools',
    'Lumos': 'Developer Tools',
    'mabl': 'Developer Tools',
    'Make': 'Developer Tools',
    'MariaDB plc': 'Developer Tools',
    'Mattermost': 'Developer Tools',
    'Merge API': 'Developer Tools',
    'MinIO': 'Developer Tools',
    'Minitab': 'Developer Tools',
    'Miro': 'Developer Tools',
    'Mitsogo Inc': 'Developer Tools',
    'Platform.sh': 'Developer Tools',
    'Posit': 'Developer Tools',
    'PQShield': 'Developer Tools',
    'Pressable': 'Developer Tools',
    'Prismatic': 'Developer Tools',
    'PubNub': 'Developer Tools',
    'Pulumi': 'Developer Tools',
    'Pure Storage': 'Developer Tools',
    'Railsware': 'Developer Tools',
    'RapidFort, Inc.': 'Developer Tools',
    'Readdle': 'Developer Tools',
    'Redwood Software': 'Developer Tools',
    'Reflex': 'Developer Tools',
    'Render': 'Developer Tools',
    'Rootstrap': 'Developer Tools',
    'Runpod, Inc.': 'Developer Tools',
    'Sanity': 'Developer Tools',
    'Scandit': 'Developer Tools',
    'Sentry': 'Developer Tools',
    'Temporal': 'Developer Tools',
    'Testlio': 'Developer Tools',
    'TiDB': 'Developer Tools',
    'TigGraph': 'Developer Tools',
    'Tines': 'Developer Tools',
    'Toradex': 'Developer Tools',
    'Trace3': 'Developer Tools',
    'Tulip Interfaces': 'Developer Tools',
    'Tucows': 'Developer Tools',
    'Tucows Domains': 'Developer Tools',
    'Tucows Inc.': 'Developer Tools',
    'Upbound': 'Developer Tools',
    'Upbound - Job Posting': 'Developer Tools',
    'Veeam Software': 'Developer Tools',
    'Velir': 'Developer Tools',
    'Vonage': 'Developer Tools',
    'Wasabi': 'Developer Tools',
    'Webflow': 'Developer Tools',
    'Webstacks': 'Developer Tools',
    'WIZELINE': 'Developer Tools',
    'Quisitive': 'Developer Tools',

    # ── Security ─────────────────────────────────────────────────────────────
    'A-LIGN External': 'Security',
    'Alarm.com': 'Security',
    'Alethea': 'Security',
    'AMAROK': 'Security',
    'Analyst1': 'Security',
    'Andesite': 'Security',
    'Apiiro': 'Security',
    'AppOmni': 'Security',
    'AppViewX': 'Security',
    'Arkose Labs': 'Security',
    'At-Bay': 'InsurTech',
    'Aura': 'Security',
    'Automox': 'Security',
    'Black Duck Software, Inc.': 'Security',
    'Blumira': 'Security',
    'Brinqa': 'Security',
    'Britive': 'Security',
    'Coalition - France': 'InsurTech',
    'DataGrail': 'Security',
    'Deepwatch': 'Security',
    'Deepwatch India': 'Security',
    'DigiCert': 'Security',
    'Digital Hands': 'Security',
    'DNSFilter': 'Security',
    'Dragos': 'Security',
    'Druva': 'Security',
    'ExpressVPN': 'Security',
    'Keyfactor, Inc.': 'Security',
    'KnowBe4': 'Security',
    'LastPass': 'Security',
    'Lookout': 'Security',
    'Lookout Inc': 'Security',
    'Pindrop': 'Security',
    'Praetorian': 'Security',
    'Private Identity': 'Security',
    'Proton': 'Security',
    'RadiantSecurity': 'Security',
    'RapidSOS': 'Security',
    'Raptor Technologies': 'Security',
    'Recorded Future': 'Security',
    'RegScale': 'Security',
    'Risk Ledger': 'Security',
    'runZero': 'Security',
    'SafeBreach': 'Security',
    'Salt Security': 'Security',
    'Securly': 'Security',
    'Thoropass': 'Security',
    'ThreatLocker': 'Security',
    'Tigera': 'Security',
    'Token Security': 'Security',
    'Torq': 'Security',
    'Transmit Security': 'Security',
    'Truffle Security': 'Security',
    'Trust Automation': 'Security',
    'Trustpilot': 'Security',  # actually review platform — better B2B SaaS
    'Vanta': 'Security',
    'Vectra': 'Security',
    'Veracode': 'Security',
    'Veriff': 'Security',
    'Verifone': 'Security',
    'Virtru': 'Security',
    'VulnCheck': 'Security',
    'Walden Security': 'Security',
    'Cymulate': 'Security',
    'Qohash': 'Security',

    # ── HR Tech ───────────────────────────────────────────────────────────────
    '12twenty': 'HR Tech',
    'ALKU': 'HR Tech',
    'ALKU - Apply Today!': 'HR Tech',
    'Amoria Group': 'HR Tech',
    'Atlas HXM': 'HR Tech',
    'Awardco': 'HR Tech',
    'BambooHR': 'HR Tech',
    'Benevity': 'HR Tech',
    'Bridgeway Benefit Technologies': 'HR Tech',
    'Brightmode': 'HR Tech',
    'Bright Network': 'HR Tech',
    'bswift': 'HR Tech',
    'Businessolver': 'HR Tech',
    'Daggerwing Group': 'HR Tech',
    'Degreed': 'HR Tech',
    'DHI Group, Inc.': 'HR Tech',
    'Energage': 'HR Tech',
    'Enboarder': 'HR Tech',
    'Envision Consulting': 'HR Tech',
    'Envoy Global, Inc.': 'HR Tech',
    'Espresa': 'HR Tech',
    'InStride': 'HR Tech',
    'Intellum, Inc.': 'HR Tech',
    'Karat': 'HR Tech',
    'LearnUpon': 'HR Tech',
    'Leapsome': 'HR Tech',
    'Level Access': 'HR Tech',
    'Litmos': 'HR Tech',
    'memoryBlue': 'HR Tech',
    'Mento': 'HR Tech',
    'Merit America': 'HR Tech',
    'Nourish': 'HR Tech',
    'Paradox': 'HR Tech',
    'Pave': 'HR Tech',
    'Per Scholas': 'HR Tech',
    'Performance Development Group': 'HR Tech',
    'Predictive Index': 'HR Tech',
    'Process Street': 'HR Tech',
    'RippleMatch': 'HR Tech',
    'SeekOut': 'HR Tech',
    'Textio': 'HR Tech',
    'The Predictive Index': 'HR Tech',
    'Togetherwork': 'HR Tech',
    'Visier Solutions Inc': 'HR Tech',
    'Workera AI': 'HR Tech',
    'Workhelix': 'HR Tech',
    'Workleap - en': 'HR Tech',
    'Workleap - fr': 'HR Tech',
    'Workstream': 'HR Tech',
    'Workwize': 'HR Tech',
    'Andgo Systems': 'HR Tech',

    # ── EdTech ───────────────────────────────────────────────────────────────
    'ALX Africa': 'EdTech',
    'American Institutes for Research': 'EdTech',
    'AppleTree Prep': 'EdTech',
    'BenchPrep': 'EdTech',
    'BrainPOP': 'EdTech',
    'BrainStation': 'EdTech',
    'Bridge to Enter Advanced Mathematics (BEAM)': 'EdTech',
    'D2L': 'EdTech',
    'DataCamp': 'EdTech',
    'Edmentum': 'EdTech',
    'EdReports': 'EdTech',
    'edX Bootcamps Instructional Engagement (Internal posts ONLY)': 'EdTech',
    'EverDriven': 'EdTech',
    'East Harlem Tutorial Program': 'EdTech',
    'Bee Genius': 'EdTech',
    'DonorsChoose': 'EdTech',
    'Encoura': 'EdTech',
    'Epic Kids Inc.': 'EdTech',
    'FasterCapital': 'EdTech',
    'Follett Software, LLC': 'EdTech',
    'General Assembly': 'EdTech',
    'IXL Learning': 'EdTech',
    'Learneo': 'EdTech',
    'LearnLux': 'EdTech',
    'Liaison International': 'EdTech',
    'Lightspeed Systems': 'EdTech',
    'LINQ': 'EdTech',
    'Minno': 'EdTech',
    'Mintel': 'EdTech',
    'NovoEd': 'EdTech',
    'Pansophic Learning': 'EdTech',
    'Pathstream': 'EdTech',
    'Praxis': 'EdTech',
    'Product School': 'EdTech',
    'QuestBridge': 'EdTech',
    'QuillBot': 'EdTech',
    'Renaissance Learning EMEA APAC': 'EdTech',
    'Renaissance Learning North America': 'EdTech',
    'SchoolMint': 'EdTech',
    'SchoolStatus': 'EdTech',
    'Seesaw': 'EdTech',
    'Teach For All': 'EdTech',
    'Teaching Lab': 'EdTech',
    'Teachstone': 'EdTech',
    'Think Academy US': 'EdTech',
    'Thinkific': 'EdTech',
    'Tidewater Tech': 'EdTech',
    'Vivvi Early Learning': 'EdTech',
    'WorldStrides': 'EdTech',
    'Yousician': 'EdTech',

    # ── Media & Entertainment ────────────────────────────────────────────────
    '143 Studios LLC': 'Media & Entertainment',
    'AIP Publishing': 'Media & Entertainment',
    'Angel City': 'Media & Entertainment',
    'Athletics - Baseball Operations': 'Media & Entertainment',
    'Athletics - Business Operations': 'Media & Entertainment',
    'AXS': 'Media & Entertainment',
    'Aylo Careers': 'Media & Entertainment',
    'Curve Royalty Systems': 'Media & Entertainment',
    'Dcard': 'Media & Entertainment',
    'David Zwirner': 'Media & Entertainment',
    'Denver Broncos and Stadium Management Company': 'Media & Entertainment',
    'Detroit Lions': 'Media & Entertainment',
    'DistroKid': 'Media & Entertainment',
    'dmg events': 'Media & Entertainment',
    'Eventbrite, Inc.': 'Media & Entertainment',
    'Excel Sports Management': 'Media & Entertainment',
    'Fender': 'Media & Entertainment',
    'FeverUp': 'Media & Entertainment',
    'The Florida Panthers': 'Media & Entertainment',
    'The Fork': 'Media & Entertainment',
    'Forbes': 'Media & Entertainment',
    'Fubo': 'Media & Entertainment',
    'Genius Sports': 'Media & Entertainment',
    'Jomboy Media': 'Media & Entertainment',
    'JCDecaux Australia': 'Media & Entertainment',
    'Landmark Theatres': 'Media & Entertainment',
    'Major League Baseball': 'Media & Entertainment',
    'Mark Morris Dance Group': 'Media & Entertainment',
    'Mechanical Licensing Collective': 'Media & Entertainment',
    'MLB Data Operations': 'Media & Entertainment',
    'MLB FFP': 'Media & Entertainment',
    'MLB (Job Board Only)': 'Media & Entertainment',
    'Mob Entertainment': 'Media & Entertainment',
    'MrBeast Contract Jobs': 'Media & Entertainment',
    'Penske Media Corp.': 'Media & Entertainment',
    'Philadelphia Eagles': 'Media & Entertainment',
    'Philadelphia Eagles Game Day Staff': 'Media & Entertainment',
    'Philadelphia Phillies - Baseball Operations': 'Media & Entertainment',
    'Philadelphia Phillies - Game Day': 'Media & Entertainment',
    'Philo': 'Media & Entertainment',
    'Playworks': 'Media & Entertainment',
    'ProPublica': 'Media & Entertainment',
    'ProPublica Opportunities': 'Media & Entertainment',
    'RTINGS.com': 'Media & Entertainment',
    'RTINGS.com (FR)': 'Media & Entertainment',
    'RUE GILT GROUPE': 'E-commerce & Retail',
    'SeatGeek': 'Media & Entertainment',
    'Seattle Sounders FC & Seattle Reign FC': 'Media & Entertainment',
    'Semafor': 'Media & Entertainment',
    'TEGNA Inc.': 'Media & Entertainment',
    'The Business of Fashion': 'Media & Entertainment',
    'The Daily Beast': 'Media & Entertainment',
    'The Economist Group': 'Media & Entertainment',
    'The Gersh Agency': 'Media & Entertainment',
    'The Motley Fool': 'Media & Entertainment',
    'The New York Times': 'Media & Entertainment',
    'The Orchard': 'Media & Entertainment',
    'Townsquare Media': 'Media & Entertainment',
    'Tubi': 'Media & Entertainment',
    'UnitedMasters | Translation': 'Media & Entertainment',
    'Universal Audio': 'Media & Entertainment',
    'Vivid Seats': 'Media & Entertainment',
    'Vox Media': 'Media & Entertainment',
    'Warner Bros. Pictures Animation': 'Media & Entertainment',
    'World Surf League': 'Media & Entertainment',
    'World Resources Institute': 'Other',

    # ── Logistics & Supply Chain ─────────────────────────────────────────────
    'Airspace': 'Logistics & Supply Chain',
    'Alvys': 'Logistics & Supply Chain',
    'Armstrong Transport Group': 'Logistics & Supply Chain',
    'Auctane': 'Logistics & Supply Chain',
    'DoorDash Australia': 'Logistics & Supply Chain',
    'DoorDash Brazil': 'Logistics & Supply Chain',
    'DoorDash Canada': 'Logistics & Supply Chain',
    'DoorDash India': 'Logistics & Supply Chain',
    'DoorDash Mexico': 'Logistics & Supply Chain',
    'DoorDash USA': 'Logistics & Supply Chain',
    'e2open': 'Logistics & Supply Chain',
    'ecosio': 'Logistics & Supply Chain',
    'ESW': 'Logistics & Supply Chain',
    'Fusion Worldwide': 'Logistics & Supply Chain',
    'ITS Logistics, LLC': 'Logistics & Supply Chain',
    'Mallory Alexander International Logistics': 'Logistics & Supply Chain',
    'MegaCorp Logistics': 'Logistics & Supply Chain',
    'Merchants Fleet': 'Logistics & Supply Chain',
    'Motive': 'Logistics & Supply Chain',
    'Roadie': 'Logistics & Supply Chain',
    'Sendcloud': 'Logistics & Supply Chain',
    'Trackonomy': 'Logistics & Supply Chain',
    'Trinity Logistics': 'Logistics & Supply Chain',
    'Truckstop': 'Logistics & Supply Chain',
    'RELEX Solutions': 'Logistics & Supply Chain',

    # ── Travel & Hospitality ──────────────────────────────────────────────────
    'Amenitiz': 'Travel & Hospitality',
    'Air North': 'Travel & Hospitality',
    'Breeze Airways™': 'Travel & Hospitality',
    'Breezeway': 'Travel & Hospitality',
    'Cabin': 'Travel & Hospitality',
    'Destination Canada': 'Travel & Hospitality',
    'Destination Canada (français)': 'Travel & Hospitality',
    'Dorsia': 'Travel & Hospitality',
    'Duetto Research': 'Travel & Hospitality',
    'Engine': 'Travel & Hospitality',
    'Evolve': 'Travel & Hospitality',
    'FlightHub': 'Travel & Hospitality',
    'FlyFlat': 'Travel & Hospitality',
    'Fora': 'Travel & Hospitality',
    'iSeatz': 'Travel & Hospitality',
    'JetInsight': 'Travel & Hospitality',
    'Kimpton Seafire Resort & Spa | Hotel Indigo Grand Cayman': 'Travel & Hospitality',
    'Lanes & Planes': 'Travel & Hospitality',
    'Mews': 'Travel & Hospitality',
    'ResortPass': 'Travel & Hospitality',
    'Rocket Travel, Inc.': 'Travel & Hospitality',
    'The Mather in Evanston': 'Travel & Hospitality',
    'The Mather in Tysons': 'Travel & Hospitality',
    'TripArc': 'Travel & Hospitality',
    'Trivago': 'Travel & Hospitality',
    'Ventura TRAVEL': 'Travel & Hospitality',
    'viagogo': 'Travel & Hospitality',
    'Vacation Inc.': 'Travel & Hospitality',
    'BLACKLANE': 'Travel & Hospitality',

    # ── PropTech ─────────────────────────────────────────────────────────────
    'Asset Living': 'PropTech',
    'Birgo': 'PropTech',
    'Block Renovation': 'PropTech',
    'Bosa Properties Inc.': 'PropTech',
    'Bozzuto': 'PropTech',
    'Dealpath': 'PropTech',
    'Digs': 'PropTech',
    'Doma Technology LLC': 'PropTech',
    'Fairstead ESC LLC': 'PropTech',
    'Faropoint': 'PropTech',
    'Flock Homes': 'PropTech',
    'Jobs @ Wunderflats': 'PropTech',
    'Lincoln Property Company': 'PropTech',
    'Lincoln Property Company through LinkedIn': 'PropTech',
    'LRK': 'PropTech',
    'LS3P': 'PropTech',
    'MG Properties': 'PropTech',
    'PlanOmatic': 'PropTech',
    'PlanRadar GmbH': 'PropTech',
    'PropHero': 'PropTech',
    'Propstack GmbH': 'PropTech',
    'Prophia': 'PropTech',
    'RCLCO': 'PropTech',
    'Redstone Residential': 'PropTech',
    'Re-Leased': 'PropTech',
    'Rexford Industrial': 'PropTech',
    'Roofr': 'PropTech',
    'Roofstock': 'PropTech',
    'The Agency': 'PropTech',
    'The Scion Group': 'PropTech',
    'Truehold': 'PropTech',
    'TurboTenant': 'PropTech',
    'Unison': 'PropTech',
    'Unlock': 'PropTech',
    'Van Metre Companies': 'PropTech',
    'Vertical Bridge': 'PropTech',
    'Weinstein Properties': 'PropTech',
    'Wheelhouse': 'PropTech',

    # ── Legal Tech ───────────────────────────────────────────────────────────
    'Brandon J. Broderick': 'Legal Tech',
    'Everchron': 'Legal Tech',
    'Eudia': 'Legal Tech',
    'eScribers': 'Legal Tech',
    'Foley Hoag LLP': 'Legal Tech',
    'Foot Anstey LLP': 'Legal Tech',
    'Keller Postman': 'Legal Tech',
    'Koley Jessen P.C., L.L.O': 'Legal Tech',
    'Kostelanetz LLP': 'Legal Tech',
    'LinkSquares, Inc.': 'Legal Tech',
    'Litify': 'Legal Tech',
    'Practising Law Institute': 'Legal Tech',
    'Rocket Lawyer': 'Legal Tech',
    'Tyson & Mendes LLP': 'Legal Tech',
    'Wilson Elser - Attorneys': 'Legal Tech',
    'Wilson Elser - Business & Legal Professionals': 'Legal Tech',
    'Witherite Law Group': 'Legal Tech',
    'Mitratech': 'Legal Tech',

    # ── InsurTech ─────────────────────────────────────────────────────────────
    'At-Bay': 'InsurTech',
    'Attune': 'InsurTech',
    'AWL': 'InsurTech',
    'Axle': 'InsurTech',
    'Coalition - France': 'InsurTech',
    'EPIC Brokers': 'InsurTech',
    'Extend': 'InsurTech',
    'First Connect Insurance': 'InsurTech',
    'Foundation Risk Partners': 'InsurTech',
    'Kalepa': 'InsurTech',
    'Lamb Insurance Services': 'InsurTech',
    'Marquee Insurance Group, LLC': 'InsurTech',
    'MEMIC': 'InsurTech',
    'MGT Insurance': 'InsurTech',
    'Paragon Insurance Holdings': 'InsurTech',
    'Pinnacol Assurance': 'InsurTech',
    'Policy Expert': 'InsurTech',
    'PERMA Risk Management Services': 'InsurTech',
    'Personal Risk Management Solutions': 'InsurTech',
    'SageSure': 'InsurTech',
    'Wakam': 'InsurTech',
    'WithCoverage': 'InsurTech',

    # ── Climate & Energy ─────────────────────────────────────────────────────
    'ACT Group': 'Climate & Energy',
    'Aircapture': 'Climate & Energy',
    'Arcadia': 'Climate & Energy',
    'Atwell, LLC': 'Climate & Energy',
    'Avantium': 'Climate & Energy',
    'Avnos': 'Climate & Energy',
    'Braskem': 'Climate & Energy',
    'DB E.C.O. North America': 'Climate & Energy',
    'Electra': 'Climate & Energy',
    'Electreon': 'Climate & Energy',
    'Electric Hydrogen': 'Climate & Energy',
    'EnSafe Inc.': 'Climate & Energy',
    'Environmental Science Associates': 'Climate & Energy',
    'EOLA Power': 'Climate & Energy',
    'ecoworks': 'Climate & Energy',
    'Ever.Ag': 'Climate & Energy',
    'ExperiGreen': 'Climate & Energy',
    'GreenSpark': 'Climate & Energy',
    'Markforged': 'Climate & Energy',
    'RoadRunner Recycling Inc.': 'Climate & Energy',
    'San Diego Community Power': 'Climate & Energy',
    'The Nuclear Company': 'Climate & Energy',
    'Too Good To Go': 'Climate & Energy',
    'Triumvirate Environmental': 'Climate & Energy',
    'Venture Global LNG': 'Climate & Energy',
    'VEIR': 'Climate & Energy',

    # ── GovTech & Defense ────────────────────────────────────────────────────
    'AGE Solutions': 'GovTech & Defense',
    'Agile Six Applications': 'GovTech & Defense',
    'Allen Control Systems': 'GovTech & Defense',
    'Allen Integrated Solutions': 'GovTech & Defense',
    'Arlo Solutions LLC': 'GovTech & Defense',
    'A-TEK Inc.': 'GovTech & Defense',
    'Attain Partners': 'GovTech & Defense',
    'Autura': 'GovTech & Defense',
    'Axon': 'GovTech & Defense',
    'AXON': 'GovTech & Defense',
    'Babel Street': 'GovTech & Defense',
    'BGE, Inc': 'GovTech & Defense',
    'Black Canyon Consulting': 'GovTech & Defense',
    'Blue Water Thinking': 'GovTech & Defense',
    'BTI360 Website': 'GovTech & Defense',
    'Data Systems Analysts, Inc.': 'GovTech & Defense',
    'Decima International': 'GovTech & Defense',
    'DelCor Technology Solutions': 'GovTech & Defense',
    'Dev Technology': 'GovTech & Defense',
    'DLH': 'GovTech & Defense',
    'Dynamis, Inc.': 'GovTech & Defense',
    'ELEVI Associates': 'GovTech & Defense',
    'Edison Scientific': 'GovTech & Defense',
    'ENSCO - Hot Jobs': 'GovTech & Defense',
    'ENSCO, Inc.': 'GovTech & Defense',
    'Excella': 'GovTech & Defense',
    'Ameelio': 'GovTech & Defense',
    'Analytic Services Inc': 'GovTech & Defense',
    'Apex Companies': 'GovTech & Defense',
    'Apex Companies - CSW': 'GovTech & Defense',
    'IntelliDyne Jobs for Veterans': 'GovTech & Defense',
    'Janes': 'GovTech & Defense',
    'The Kenjya-Trusant Group , LLC': 'GovTech & Defense',
    'LIGHTFEATHER IO LLC': 'GovTech & Defense',
    'Loft Federal': 'GovTech & Defense',
    'Mark43': 'GovTech & Defense',
    'MetroStar': 'GovTech & Defense',
    'MKS2 Technologies': 'GovTech & Defense',
    'Pluribus Digital': 'GovTech & Defense',
    'PublicInput': 'GovTech & Defense',
    'Raft Company Website': 'GovTech & Defense',
    'Raptor Technologies': 'GovTech & Defense',
    'Recidiviz': 'GovTech & Defense',
    'Rise8': 'GovTech & Defense',
    'Sandboxx': 'GovTech & Defense',
    'Technical Assent': 'GovTech & Defense',
    'Technergetics': 'GovTech & Defense',
    'T-Rex Solutions': 'GovTech & Defense',
    'Two Six Technologies': 'GovTech & Defense',
    'TurbineOne': 'GovTech & Defense',
    'UASI': 'GovTech & Defense',
    'Unanet': 'GovTech & Defense',
    'Versaterm': 'GovTech & Defense',
    'Voyager Technologies, Inc.': 'GovTech & Defense',
    'Vot-ER': 'GovTech & Defense',
    'AJ Boggs/ProPower': 'GovTech & Defense',
    'BMNT': 'GovTech & Defense',
    'eSCRIBE': 'GovTech & Defense',

    # ── Automotive & Mobility ────────────────────────────────────────────────
    'Affinitiv': 'Marketing Tech',  # automotive marketing, not automotive
    'Agero': 'Automotive & Mobility',
    'Aperia': 'Automotive & Mobility',
    'Archer': 'Automotive & Mobility',
    'AutoProff': 'Automotive & Mobility',
    'AutoScout24': 'Automotive & Mobility',
    'AutoTrader.ca': 'Automotive & Mobility',
    'Cabify': 'Automotive & Mobility',
    'FREENOW': 'Automotive & Mobility',
    'Geotab': 'Automotive & Mobility',
    'JetZero': 'SpaceTech',
    'Lightspeed DMS': 'Automotive & Mobility',
    'Lotlinx': 'Automotive & Mobility',
    'Mitsubishi Motors North America, Inc.': 'Automotive & Mobility',
    'Scout24': 'Automotive & Mobility',
    'Tekion': 'Automotive & Mobility',
    'Tekmetric': 'Automotive & Mobility',
    'Via': 'Automotive & Mobility',
    'Verra Mobility': 'Automotive & Mobility',
    'Xometry': 'Robotics & Hardware',

    # ── Robotics & Hardware ──────────────────────────────────────────────────
    'Ambiq Micro, Inc.': 'Robotics & Hardware',
    'AON3D Careers': 'Robotics & Hardware',
    'aPriori': 'Robotics & Hardware',
    'AssetWatch, Inc.': 'Robotics & Hardware',
    'Atomic Machines': 'Robotics & Hardware',
    'Augury': 'Robotics & Hardware',
    'Axis Automation': 'Robotics & Hardware',
    'Blue River Technology': 'Robotics & Hardware',
    'Butlr': 'Robotics & Hardware',
    'CADimensions, Inc.': 'Robotics & Hardware',
    'Cerebras': 'Robotics & Hardware',
    'Designed Conveyor Systems': 'Robotics & Hardware',
    'Dexory': 'Robotics & Hardware',
    'Dirac, Inc.': 'Robotics & Hardware',
    'Divergent': 'Robotics & Hardware',
    'Efficient Computer': 'Robotics & Hardware',
    'EOS': 'Robotics & Hardware',
    'Etched': 'Robotics & Hardware',
    'Formlabs': 'Robotics & Hardware',
    'Lightmatter': 'Robotics & Hardware',
    'Lucid Bots': 'Robotics & Hardware',
    'Magic Leap': 'Robotics & Hardware',
    'Magic Leap - Multiple Locations': 'Robotics & Hardware',
    'MatX': 'Robotics & Hardware',
    'Maxcess International': 'Robotics & Hardware',
    'MetOx International, Inc.': 'Robotics & Hardware',
    'Parsec Automation Corp.': 'Robotics & Hardware',
    'Phoenix Contact': 'Robotics & Hardware',
    'Piston Technologies': 'Robotics & Hardware',
    'Roboyo': 'Robotics & Hardware',
    'Rugged Robotics': 'Robotics & Hardware',
    'Samsung Semiconductor': 'Robotics & Hardware',
    'Tenstorrent': 'Robotics & Hardware',
    'Third Wave Automation': 'Robotics & Hardware',
    'Torc Robotics': 'Automotive & Mobility',
    'Trust Automation': 'Robotics & Hardware',
    'Xometry': 'Robotics & Hardware',

    # ── SpaceTech ────────────────────────────────────────────────────────────
    'Isar Aerospace SE': 'SpaceTech',
    'JetZero': 'SpaceTech',
    'K2 Space': 'SpaceTech',
    'Katalyst Space Technologies': 'SpaceTech',
    'KH Aerospace': 'SpaceTech',
    'LeoLabs, Inc.': 'SpaceTech',
    'Muon Space': 'SpaceTech',
    'Orbital Insight': 'SpaceTech',
    'Rhombus Power, Inc.': 'SpaceTech',
    'Samara Aerospace': 'SpaceTech',
    'True Anomaly': 'SpaceTech',
    'Ursa Major': 'SpaceTech',
    'Varda Space Industries': 'SpaceTech',
    'Vast': 'SpaceTech',

    # ── Biotech & Pharma ─────────────────────────────────────────────────────
    'Aralez Bio': 'Biotech & Pharma',
    'Arvinas': 'Biotech & Pharma',
    'Aspect Biosystems': 'Biotech & Pharma',
    'BridgeBio Pharma': 'Biotech & Pharma',
    'Calicolabs': 'Biotech & Pharma',
    'EVERY™': 'Biotech & Pharma',
    'Freenome': 'Biotech & Pharma',
    'Integral Molecular': 'Biotech & Pharma',
    'Kincell Bio, LLC': 'Biotech & Pharma',
    'Manifold Bio': 'Biotech & Pharma',
    'Maravai LifeSciences': 'Biotech & Pharma',
    'Profluent': 'Biotech & Pharma',
    'Protillion Biosciences': 'Biotech & Pharma',
    'Pulmovant': 'Biotech & Pharma',
    'Third Pole, Inc.': 'Biotech & Pharma',
    'Variant Bio': 'Biotech & Pharma',
    'Vedanta Biosciences': 'Biotech & Pharma',
    'Vir Biotechnology': 'Biotech & Pharma',
    'Vor Bio': 'Biotech & Pharma',

    # ── AI/ML ─────────────────────────────────────────────────────────────────
    'Airia': 'AI/ML',
    'Biograph': 'AI/ML',
    'DeepMind': 'AI/ML',
    'Enterra Solutions': 'AI/ML',
    'IonQ': 'AI/ML',
    'PhysicsX': 'AI/ML',
    'PsiQuantum': 'AI/ML',
    'QuEra Computing, Inc.': 'AI/ML',
    'QuiX Quantum BV': 'AI/ML',
    'Quantum-Si': 'AI/ML',
    'Vultron.ai': 'AI/ML',
    'World Labs': 'AI/ML',

    # ── Data & Analytics ─────────────────────────────────────────────────────
    'Amperity': 'Data & Analytics',
    'Antenna': 'Data & Analytics',
    'Beauhurst': 'Data & Analytics',
    'BlastPoint': 'Data & Analytics',
    'Brandwatch': 'Data & Analytics',
    'Databento': 'Data & Analytics',
    'DAS42': 'Data & Analytics',
    'Domino Data Lab': 'Data & Analytics',
    'dunnhumby': 'Data & Analytics',
    'Enigma': 'Data & Analytics',
    'Enformion': 'Data & Analytics',
    'Eqvilent': 'Data & Analytics',
    'Emendata': 'Data & Analytics',
    'Forward Networks': 'Data & Analytics',
    'Mintel': 'Data & Analytics',
    'Mirakl': 'Data & Analytics',
    'PitchBook Data': 'Data & Analytics',
    'Quansight': 'Data & Analytics',
    'Reach3 Insights': 'Data & Analytics',
    'Resonate': 'Data & Analytics',
    'Retail Insights': 'Data & Analytics',
    'RetailNext': 'Data & Analytics',
    'Savoy Life': 'Data & Analytics',
    'SciLeads': 'Data & Analytics',
    'Yellowbrick Data': 'Data & Analytics',

    # ── Consumer & Social ────────────────────────────────────────────────────
    'Betsson Group': 'Gaming',
    'Brooklyn Sports & Entertainment': 'Media & Entertainment',
    'Kickstarter PBC': 'Consumer & Social',
    'Life360': 'Consumer & Social',
    'Mighty Networks': 'Consumer & Social',
    'VSCO': 'Consumer & Social',
    'Wallapop': 'E-commerce & Retail',

    # ── B2B SaaS (catch-all horizontal software) ──────────────────────────────
    'Affinity.co': 'B2B SaaS',
    'Agilisys': 'B2B SaaS',
    'Anaplan': 'B2B SaaS',
    'Appian Corporation': 'B2B SaaS',
    'Appspace': 'B2B SaaS',
    'Arkestro': 'B2B SaaS',
    'BEES': 'B2B SaaS',
    'Bitly Inc.': 'B2B SaaS',
    'Blackthorn.io': 'B2B SaaS',
    'BlueCherry': 'B2B SaaS',
    'Boostlingo': 'B2B SaaS',
    'BuildOps': 'B2B SaaS',
    'Buynomics': 'B2B SaaS',
    'Datacor': 'B2B SaaS',
    'Decisions': 'B2B SaaS',
    'Dialpad': 'B2B SaaS',
    'Dialpad (Dialership Program)': 'B2B SaaS',
    'Documo': 'B2B SaaS',
    'DocNetwork': 'B2B SaaS',
    'Donorbox': 'B2B SaaS',
    'Durable': 'B2B SaaS',
    'Enavate': 'B2B SaaS',
    'Enhesa': 'B2B SaaS',
    'Enumerate': 'B2B SaaS',
    'Eon': 'B2B SaaS',
    'EquipmentShare': 'B2B SaaS',
    'eSCRIBE': 'B2B SaaS',
    'Espresa': 'B2B SaaS',
    'Evismart': 'B2B SaaS',
    'ezCater, Inc': 'B2B SaaS',
    'FastSpring': 'B2B SaaS',
    'Fieldwire': 'B2B SaaS',
    'Fellow': 'B2B SaaS',
    'Five9': 'B2B SaaS',
    'Gladly': 'B2B SaaS',
    'InvGate': 'B2B SaaS',
    'Jama Software': 'B2B SaaS',
    'Jellyvision': 'B2B SaaS',
    'Kaseya Careers': 'B2B SaaS',
    'Kasisto': 'B2B SaaS',
    'KONUX': 'B2B SaaS',
    'Leapwork': 'B2B SaaS',
    'LogicGate': 'B2B SaaS',
    'Logiwa': 'B2B SaaS',
    'Lucid Software': 'B2B SaaS',
    'MaintainX': 'B2B SaaS',
    'MasterControl': 'B2B SaaS',
    'Materialize': 'B2B SaaS',
    'Mattermost': 'B2B SaaS',
    'Momence': 'B2B SaaS',
    'Poppulo': 'B2B SaaS',
    'Proalpha Group': 'B2B SaaS',
    'Process Street': 'B2B SaaS',
    'ROLLER': 'B2B SaaS',
    'Rithum': 'B2B SaaS',
    'Torii': 'B2B SaaS',
    'Trustpilot': 'B2B SaaS',
    'UJET': 'B2B SaaS',
    'UpKeep': 'B2B SaaS',
    'Upshop': 'B2B SaaS',
    'Varicent': 'B2B SaaS',
    'Veeam Software': 'B2B SaaS',
    'Vibes': 'B2B SaaS',
    'WorkBoard': 'B2B SaaS',
    'VTEX': 'B2B SaaS',
}

app = create_app()
with app.app_context():
    updated = 0
    not_found = []
    for name, industry in OVERRIDES.items():
        companies = Company.query.filter_by(name=name, is_active=True).all()
        if not companies:
            not_found.append(name)
            continue
        for c in companies:
            if c.industry != industry:
                print(f"  {c.name:<50} {str(c.industry):<25} → {industry}")
                if APPLY:
                    c.industry = industry
                updated += 1

    if APPLY:
        db.session.commit()

    print(f"\n{'Applied' if APPLY else 'Would update'}: {updated} companies")
    if not_found:
        print(f"Not found ({len(not_found)}): {', '.join(not_found[:20])}{'...' if len(not_found)>20 else ''}")
    if not APPLY:
        print("Re-run with --apply to write.")
