#!/usr/bin/env python3
"""
Discover which companies from a large seed list use Greenhouse ATS.

Usage:
    # Use built-in seed list
    python scripts/discover_greenhouse_companies.py

    # Use an external JSON file of slugs (e.g. from Feashliaa dataset)
    python scripts/discover_greenhouse_companies.py --from-file /tmp/greenhouse_all_slugs.json

    python scripts/discover_greenhouse_companies.py --min-jobs 1 --concurrency 50
    python scripts/discover_greenhouse_companies.py --output results.csv

Outputs confirmed companies sorted by job count, skipping ones already in companies.py or the prod DB.
"""

import asyncio
import aiohttp
import argparse
import csv
import json
import os
import re
import sys
import time
from typing import Optional

# ── Already tracked ──────────────────────────────────────────────────────────
sys.path.insert(0, "/Users/henry_c/WhatsInDemand/backend")
from app.scrapers.companies import COMPANIES

EXISTING_SLUGS = {c["slug"] for c in COMPANIES if c["ats"] == "greenhouse"}

# Also pull slugs from the prod DB so we don't re-add companies already scraped
def _load_db_slugs() -> set:
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        print("DATABASE_URL not set — skipping DB slug check.")
        return set()
    try:
        import psycopg
        conn = psycopg.connect(db_url)
        cur = conn.cursor()
        cur.execute("SELECT greenhouse_slug FROM companies WHERE greenhouse_slug IS NOT NULL")
        slugs = {row[0] for row in cur.fetchall()}
        cur.close()
        conn.close()
        print(f"Loaded {len(slugs)} slugs from prod DB.")
        return slugs
    except Exception as e:
        print(f"Warning: could not load DB slugs ({e}). Falling back to companies.py only.")
        return set()

EXISTING_SLUGS |= _load_db_slugs()

# ── Seed list ─────────────────────────────────────────────────────────────────
# (name, slug_hint)  — slug_hint is our best guess; script also tries variations
SEED = [
    # AI / ML
    ("Cohere", "cohere"),
    ("Hugging Face", "huggingface"),
    ("Mistral AI", "mistral"),
    ("Inflection AI", "inflection"),
    ("Adept AI", "adept"),
    ("Character AI", "characterai"),
    ("Weights & Biases", "wandb"),
    ("Replicate", "replicate"),
    ("Midjourney", "midjourney"),
    ("Pika", "pika"),
    ("Luma AI", "lumalabs"),
    ("Krea AI", "krea"),
    ("Ideogram", "ideogram"),
    ("Suno", "suno"),
    ("Udio", "udio"),
    ("Magic", "magic"),
    ("Contextual AI", "contextualai"),
    ("Prior Labs", "priorlabs"),
    ("Liquid AI", "liquidai"),
    ("xAI", "xai"),
    ("Captions", "captions"),
    ("Harvey AI", "harveyai"),
    ("Casetext", "casetext"),
    ("Veritone", "veritone"),
    ("Clarifai", "clarifai"),
    ("Cognite", "cognite"),
    ("Kensho", "kensho"),
    ("DataRobot", "datarobot"),
    ("H2O.ai", "h2oai"),
    ("C3.ai", "c3"),
    ("Synthesis AI", "synthesisai"),
    ("Inworld AI", "inworld"),
    ("Moveworks", "moveworks"),
    ("Observe AI", "observeai"),
    ("Forethought AI", "forethought"),
    ("Cogito", "cogito"),

    # B2B SaaS
    ("HubSpot", "hubspot"),
    ("Zendesk", "zendesk"),
    ("Box", "box"),
    ("Twilio", "twilio"),
    ("Elastic", "elastic"),
    ("Confluent", "confluent"),
    ("PagerDuty", "pagerduty"),
    ("HashiCorp", "hashicorp"),
    ("New Relic", "newrelic"),
    ("Dynatrace", "dynatrace"),
    ("AppDynamics", "appdynamics"),
    ("Mulesoft", "mulesoft"),
    ("Zuora", "zuora"),
    ("Veeva Systems", "veeva"),
    ("Medallia", "medallia"),
    ("Qualtrics", "qualtrics"),
    ("Sprinklr", "sprinklr"),
    ("Freshworks", "freshworks"),
    ("Zoho", "zoho"),
    ("ServiceNow", "servicenow"),
    ("Workato", "workato"),
    ("Tray.io", "tray"),
    ("Boomi", "boomi"),
    ("Informatica", "informatica"),
    ("Talend", "talend"),
    ("Segment", "segment"),
    ("mParticle", "mparticle"),
    ("Treasure Data", "treasuredata"),
    ("Contentsquare", "contentsquare"),
    ("Heap", "heap"),
    ("FullStory", "fullstory"),
    ("Glassbox", "glassbox"),
    ("Optimizely", "optimizely"),
    ("Kameleoon", "kameleoon"),
    ("AB Tasty", "abtasty"),
    ("Iterable", "iterable"),
    ("Emarsys", "emarsys"),
    ("Listrak", "listrak"),
    ("Sendbird", "sendbird"),
    ("Twilio Segment", "twilio"),
    ("Livelike", "livelike"),
    ("Contentful", "contentful"),
    ("Contentstack", "contentstack"),
    ("Sanity", "sanity"),
    ("Storyblok", "storyblok"),
    ("Sitecore", "sitecore"),
    ("Acquia", "acquia"),
    ("Pantheon", "pantheon"),
    ("WP Engine", "wpengine"),
    ("Cloudinary", "cloudinary"),
    ("imgix", "imgix"),
    ("Bynder", "bynder"),
    ("Coda", "coda"),
    ("Guru", "guru"),
    ("Tettra", "tettra"),
    ("Confluence", "confluence"),
    ("Notion", "notion"),
    ("Slite", "slite"),
    ("Slab", "slab"),
    ("Helpjuice", "helpjuice"),
    ("Document360", "document360"),
    ("Zendesk Guide", "zendesk"),
    ("Freshdesk", "freshdesk"),
    ("Zoho Desk", "zoho"),
    ("Gorgias", "gorgias"),
    ("Gladly", "gladly"),
    ("Kustomer", "kustomer"),
    ("Dixa", "dixa"),
    ("Tidio", "tidio"),
    ("Drift", "drift"),
    ("Qualified", "qualified"),
    ("6sense", "6sense"),
    ("Demandbase", "demandbase"),
    ("TechTarget", "techtarget"),
    ("ZoomInfo", "zoominfo"),
    ("Clearbit", "clearbit"),
    ("Lusha", "lusha"),
    ("Apollo.io", "apolloio"),
    ("Seamless.AI", "seamlessai"),
    ("Outreach", "outreach"),
    ("Salesloft", "salesloft"),
    ("Groove", "groove"),
    ("Mixmax", "mixmax"),
    ("Yesware", "yesware"),
    ("Clari", "clari"),
    ("Chorus.ai", "chorus"),
    ("Gong", "gong"),
    ("Wingman", "wingman"),
    ("Jiminny", "jiminny"),
    ("Allego", "allego"),
    ("Highspot", "highspot"),
    ("Showpad", "showpad"),
    ("Mindtickle", "mindtickle"),
    ("Lessonly", "lessonly"),
    ("Seismic", "seismic"),
    ("Mediafly", "mediafly"),
    ("Reprise", "reprise"),
    ("Walnut", "walnut"),
    ("Navattic", "navattic"),
    ("Tourial", "tourial"),
    ("Consensus", "consensus"),
    ("Vidyard", "vidyard"),
    ("Loom", "loom"),
    ("Wistia", "wistia"),
    ("Vimeo", "vimeo"),
    ("Brightcove", "brightcove"),
    ("Kaltura", "kaltura"),
    ("Panopto", "panopto"),
    ("Domo", "domo"),
    ("Looker", "looker"),
    ("Mode Analytics", "mode"),
    ("Sigma Computing", "sigmacomputing"),
    ("ThoughtSpot", "thoughtspot"),
    ("Qlik", "qlik"),
    ("MicroStrategy", "microstrategy"),
    ("Sisense", "sisense"),
    ("Yellowfin", "yellowfin"),
    ("Metabase", "metabase"),
    ("Superset", "superset"),
    ("Grafana Labs", "grafana"),
    ("Splunk", "splunk"),
    ("Sumo Logic", "sumologic"),
    ("Elastic", "elastic"),
    ("Coralogix", "coralogix"),
    ("Observe Inc", "observeinc"),
    ("Honeycomb", "honeycomb"),
    ("Lightstep", "lightstep"),
    ("Chronosphere", "chronosphere"),
    ("Cribl", "cribl"),
    ("Panther Labs", "pantherlabs"),
    ("Stitch Data", "stitchdata"),
    ("Census", "census"),
    ("Hightouch", "hightouch"),
    ("Grouparoo", "grouparoo"),
    ("dbt Labs", "dbtlabs"),
    ("Atlan", "atlan"),
    ("Alation", "alation"),
    ("Collibra", "collibra"),
    ("Informatica", "informatica"),
    ("Monte Carlo", "montecarlodata"),
    ("Soda", "sodadata"),
    ("Great Expectations", "greatexpectations"),

    # Security
    ("CrowdStrike", "crowdstrike"),
    ("Palo Alto Networks", "paloaltonetworks"),
    ("SentinelOne", "sentinelone"),
    ("Tenable", "tenable"),
    ("Rapid7", "rapid7"),
    ("Qualys", "qualys"),
    ("Lacework", "lacework"),
    ("Sysdig", "sysdig"),
    ("Aqua Security", "aquasecurity"),
    ("Prisma Cloud", "prismacloud"),
    ("Cybereason", "cybereason"),
    ("Darktrace", "darktrace"),
    ("Vectra AI", "vectra"),
    ("Recorded Future", "recordedfuture"),
    ("ThreatConnect", "threatconnect"),
    ("Swimlane", "swimlane"),
    ("Exabeam", "exabeam"),
    ("LogRhythm", "logrhythm"),
    ("Securonix", "securonix"),
    ("Sumo Logic Security", "sumologic"),
    ("1Password", "1password"),
    ("Bitwarden", "bitwarden"),
    ("Dashlane", "dashlane"),
    ("NordPass", "nordpass"),
    ("Keeper Security", "keepersecurity"),
    ("Delinea", "delinea"),
    ("BeyondTrust", "beyondtrust"),
    ("CyberArk", "cyberark"),
    ("Sailpoint", "sailpoint"),
    ("ForgeRock", "forgerock"),
    ("Ping Identity", "pingidentity"),
    ("Auth0", "auth0"),
    ("Duo Security", "duo"),
    ("Yubico", "yubico"),
    ("Lumu Technologies", "lumu"),
    ("Black Kite", "blackkite"),
    ("BitSight", "bitsight"),
    ("SecurityScorecard", "securityscorecard"),
    ("RiskRecon", "riskrecon"),
    ("UpGuard", "upguard"),
    ("Panorays", "panorays"),
    ("Prevalent", "prevalent"),
    ("OneTrust", "onetrust"),
    ("TrustArc", "trustarc"),
    ("BigID", "bigid"),
    ("Privacera", "privacera"),
    ("WireWheel", "wirewheel"),
    ("Spirent", "spirent"),
    ("NetSPI", "netspi"),
    ("Bishop Fox", "bishopfox"),
    ("Synack", "synack"),
    ("HackerOne", "hackerone"),
    ("Bugcrowd", "bugcrowd"),
    ("Intigriti", "intigriti"),

    # Developer Tools / Infrastructure
    ("HashiCorp", "hashicorp"),
    ("Pulumi", "pulumi"),
    ("Spacelift", "spacelift"),
    ("Env0", "env0"),
    ("Scalr", "scalr"),
    ("Terraform Cloud", "terraform"),
    ("Architect.io", "architect"),
    ("Porter", "porter"),
    ("Skaffold", "skaffold"),
    ("Tilt", "tilt"),
    ("Garden", "garden"),
    ("Earthly", "earthly"),
    ("Dagger", "dagger"),
    ("Buildkite", "buildkite"),
    ("Harness", "harness"),
    ("Codefresh", "codefresh"),
    ("Argo CD", "argoproj"),
    ("FluxCD", "fluxcd"),
    ("Spinnaker", "spinnaker"),
    ("Octopus Deploy", "octopusdeploy"),
    ("Release", "release"),
    ("Humanitec", "humanitec"),
    ("Cortex", "cortex"),
    ("Backstage", "backstage"),
    ("OpsLevel", "opslevel"),
    ("Rootly", "rootly"),
    ("FireHydrant", "firehydrant"),
    ("Blameless", "blameless"),
    ("PagerDuty", "pagerduty"),
    ("Opsgenie", "opsgenie"),
    ("VictorOps", "victorops"),
    ("xMatters", "xmatters"),
    ("Statuspage", "statuspage"),
    ("Atlassian", "atlassian"),
    ("JFrog", "jfrog"),
    ("Sonatype", "sonatype"),
    ("Snyk", "snyk"),
    ("WhiteSource", "whitesource"),
    ("FOSSA", "fossa"),
    ("Mend.io", "mend"),
    ("Socket", "socket"),
    ("Chainguard", "chainguard"),
    ("Sigstore", "sigstore"),
    ("Slim.ai", "slimai"),
    ("Anchore", "anchore"),
    ("Clair", "clair"),
    ("Trivy", "trivy"),
    ("Grype", "grype"),
    ("Syft", "syft"),
    ("Apono", "apono"),
    ("Entitle", "entitle"),
    ("Opal Security", "opalsecurity"),
    ("Lumos", "lumos"),
    ("Indent", "indent"),
    ("Clutch", "clutch"),
    ("Cerbos", "cerbos"),
    ("Permit.io", "permit"),
    ("Hasura", "hasura"),
    ("Fauna", "fauna"),
    ("Xata", "xata"),
    ("Turso", "turso"),
    ("CockroachDB", "cockroachlabs"),
    ("SingleStore", "singlestore"),
    ("TimescaleDB", "timescale"),
    ("QuestDB", "questdb"),
    ("InfluxDB", "influxdata"),
    ("MongoDB", "mongodb"),
    ("Couchbase", "couchbase"),
    ("Redis", "redis"),
    ("Aerospike", "aerospike"),
    ("Yugabyte", "yugabyte"),
    ("Vitess", "vitess"),
    ("Percona", "percona"),
    ("MariaDB", "mariadb"),
    ("EnterpriseDB", "enterprisedb"),
    ("Snowflake", "snowflake"),
    ("Firebolt", "firebolt"),
    ("DuckDB", "duckdb"),
    ("MotherDuck", "motherduck"),
    ("Redpanda", "redpanda"),
    ("Materialize", "materialize"),
    ("Imply", "imply"),
    ("Apache Druid", "apachedruid"),
    ("Pinot", "pinot"),
    ("Rockset", "rockset"),
    ("Hydrolix", "hydrolix"),

    # Cloud / Infrastructure
    ("Fastly", "fastly"),
    ("Akamai", "akamai"),
    ("Cloudflare", "cloudflare"),
    ("NS1", "ns1"),
    ("Fly.io", "flyio"),
    ("Northflank", "northflank"),
    ("Koyeb", "koyeb"),
    ("Qovery", "qovery"),
    ("Civo", "civo"),
    ("Linode", "linode"),
    ("Vultr", "vultr"),
    ("DigitalOcean", "digitalocean"),
    ("Hetzner", "hetzner"),
    ("OVHcloud", "ovhcloud"),
    ("Equinix", "equinix"),
    ("Zenlayer", "zenlayer"),
    ("Lumen Technologies", "lumen"),
    ("Rackspace", "rackspace"),
    ("Wasabi", "wasabi"),
    ("Storj", "storj"),
    ("Backblaze", "backblaze"),
    ("Cloudflare R2", "cloudflare"),
    ("Tigris Data", "tigris"),

    # Fintech
    ("Plaid", "plaid"),
    ("Rippling", "rippling"),
    ("Navan", "navan"),
    ("Workday", "workday"),
    ("Paylocity", "paylocity"),
    ("Paychex", "paychex"),
    ("ADP", "adp"),
    ("Ceridian", "ceridian"),
    ("UKG", "ukg"),
    ("Bamboo HR", "bamboohr"),
    ("TriNet", "trinet"),
    ("Paycom", "paycom"),
    ("Zenefits", "zenefits"),
    ("Namely", "namely"),
    ("Personio", "personio"),
    ("HiBob", "hibob"),
    ("Factorial HR", "factorial"),
    ("Humaans", "humaans"),
    ("CharlieHR", "charliehr"),
    ("Keka", "keka"),
    ("GreytHR", "greythr"),
    ("Kredily", "kredily"),
    ("Darwinbox", "darwinbox"),
    ("Zoho People", "zohopeople"),
    ("SAP SuccessFactors", "sapsuccessfactors"),
    ("Oracle HCM", "oraclehcm"),
    ("Sage HR", "sagehr"),
    ("Collage HR", "collagehr"),
    ("Wagepoint", "wagepoint"),
    ("Rise People", "risepeople"),
    ("Humi", "humi"),
    ("Knit", "knit"),
    ("Papaya Global", "papayaglobal"),
    ("Velocity Global", "velocityglobal"),
    ("G-P (Globalization Partners)", "globalizationpartners"),
    ("Airwallex", "airwallex"),
    ("Wise", "wise"),
    ("Revolut", "revolut"),
    ("N26", "n26"),
    ("Starling Bank", "starlingbank"),
    ("Monzo", "monzo"),
    ("Atom Bank", "atombank"),
    ("Tandem", "tandem"),
    ("Bunq", "bunq"),
    ("Trade Republic", "traderepublic"),
    ("Scalable Capital", "scalablecapital"),
    ("Freetrade", "freetrade"),
    ("Trading 212", "trading212"),
    ("eToro", "etoro"),
    ("Public.com", "public"),
    ("Betterment", "betterment"),
    ("Wealthfront", "wealthfront"),
    ("Acorns", "acorns"),
    ("Stash", "stash"),
    ("M1 Finance", "m1finance"),
    ("Personal Capital", "personalcapital"),
    ("Ellevest", "ellevest"),
    ("Oportun", "oportun"),
    ("Dave", "dave"),
    ("Cleo", "cleo"),
    ("Digit", "digit"),
    ("Albert", "albert"),
    ("Possible Finance", "possiblefinance"),
    ("LoanSnap", "loansnap"),
    ("Better.com", "better"),
    ("Blend", "blend"),
    ("Roofstock", "roofstock"),
    ("Fundrise", "fundrise"),
    ("CrowdStreet", "crowdstreet"),
    ("Cadre", "cadre"),
    ("Yieldstreet", "yieldstreet"),
    ("Masterworks", "masterworks"),
    ("Rally", "rally"),
    ("Otis", "otis"),
    ("Vint", "vint"),
    ("Vinovest", "vinovest"),
    ("Pipe", "pipe"),
    ("Clearco", "clearco"),
    ("Capchase", "capchase"),
    ("Arc", "arc"),
    ("Founderpath", "founderpath"),
    ("Lighter Capital", "lightercapital"),
    ("Bigfoot Capital", "bigfootcapital"),
    ("Decathlon Capital", "decathloncapital"),
    ("Indie.vc", "indievc"),

    # Healthcare / Biotech
    ("Oscar Health", "hioscar"),
    ("Hims & Hers", "hims"),
    ("Noom", "noom"),
    ("Teladoc", "teladoc"),
    ("Ro", "ro"),
    ("Thirty Madison", "thirtymadison"),
    ("Cerebral", "cerebral"),
    ("Spring Health", "springhealth"),
    ("Headspace", "headspace"),
    ("Brightline", "brightline"),
    ("Lyra Health", "lyrahealth"),
    ("Ginger", "ginger"),
    ("Talkspace", "talkspace"),
    ("BetterHelp", "betterhelp"),
    ("Alma", "alma"),
    ("Grow Therapy", "growtherapy"),
    ("Path Mental Health", "pathmentalhealth"),
    ("Rula Health", "rula"),
    ("Headway", "headway"),
    ("Blueprint", "blueprint"),
    ("Suki AI", "suki"),
    ("Abridge", "abridge"),
    ("Nuance Communications", "nuance"),
    ("Augmedix", "augmedix"),
    ("Ambience Healthcare", "ambiencehealthcare"),
    ("DeepScribe", "deepscribe"),
    ("Nabla", "nabla"),
    ("Notable Health", "notable"),
    ("Olive AI", "oliveai"),
    ("Health Catalyst", "healthcatalyst"),
    ("Arcadia", "arcadia"),
    ("Innovaccer", "innovaccer"),
    ("Apixio", "apixio"),
    ("Ciox Health", "cioxhealth"),
    ("Datavant", "datavant"),
    ("Veradigm", "veradigm"),
    ("Komodo Health", "komodohealth"),
    ("Tempus", "tempus"),
    ("Foundation Medicine", "foundationmedicine"),
    ("Guardant Health", "guardanthealth"),
    ("Grail", "grail"),
    ("Color Health", "color"),
    ("Invitae", "invitae"),
    ("GeneDx", "genedx"),
    ("Ambry Genetics", "ambrygen"),
    ("Counsyl", "counsyl"),
    ("Myriad Genetics", "myriad"),
    ("Veracyte", "veracyte"),
    ("Exact Sciences", "exactsciences"),
    ("Caris Life Sciences", "carislifesciences"),
    ("Neogenomics", "neogenomics"),
    ("Illumina", "illumina"),
    ("Pacific Biosciences", "pacificbiosciences"),
    ("Oxford Nanopore", "nanoporetech"),
    ("10x Genomics", "10xgenomics"),
    ("Singleron Biotechnologies", "singleron"),
    ("Twist Bioscience", "twistbioscience"),
    ("Zymergen", "zymergen"),
    ("Ginkgo Bioworks", "ginkgobioworks"),
    ("Benchling", "benchling"),
    ("Synthego", "synthego"),
    ("Desktop Metal", "desktopmetal"),
    ("Carbon", "carbon"),
    ("Formlabs", "formlabs"),
    ("Markforged", "markforged"),
    ("Velo3D", "velo3d"),
    ("Relativity Space", "relativityspace"),
    ("ABB", "abb"),

    # E-commerce / Retail / Consumer
    ("Shopify", "shopify"),
    ("BigCommerce", "bigcommerce"),
    ("WooCommerce", "woocommerce"),
    ("Magento", "magento"),
    ("Salesforce Commerce", "commercecloud"),
    ("Bolt", "bolt"),
    ("Fast", "fast"),
    ("Checkout.com", "checkout"),
    ("Mollie", "mollie"),
    ("Klarna", "klarna"),
    ("Afterpay", "afterpay"),
    ("Zip", "zip"),
    ("Sezzle", "sezzle"),
    ("Splitit", "splitit"),
    ("Paidy", "paidy"),
    ("Atome", "atome"),
    ("Hoolah", "hoolah"),
    ("Tabby", "tabby"),
    ("Tamara", "tamara"),
    ("Postpay", "postpay"),
    ("Spotii", "spotii"),
    ("Tymit", "tymit"),
    ("Zilch", "zilch"),
    ("PayPay", "paypay"),
    ("Paidy", "paidy"),
    ("Twisto", "twisto"),
    ("Ratepay", "ratepay"),
    ("Mondu", "mondu"),
    ("Billie", "billie"),
    ("Hokodo", "hokodo"),
    ("Two", "two"),
    ("Behalf", "behalf"),
    ("Fundbox", "fundbox"),
    ("BlueVine", "bluevine"),
    ("Kabbage", "kabbage"),
    ("OnDeck", "ondeck"),
    ("Lendio", "lendio"),
    ("Nav", "nav"),
    ("Credibly", "credibly"),
    ("Rapid Finance", "rapidfinance"),
    ("Posh", "posh"),
    ("The RealReal", "therealreal"),
    ("ThredUp", "thredup"),
    ("Depop", "depop"),
    ("Vinted", "vinted"),
    ("Vestiaire Collective", "vestiairecollective"),
    ("Tradesy", "tradesy"),
    ("Rebag", "rebag"),
    ("Fashionphile", "fashionphile"),
    ("Poshmark", "poshmark"),
    ("Kidizen", "kidizen"),
    ("Yerdle", "yerdle"),
    ("Loop Returns", "loop"),
    ("Happy Returns", "happyreturns"),
    ("Returnly", "returnly"),
    ("Narvar", "narvar"),
    ("Akeneo", "akeneo"),
    ("Salsify", "salsify"),
    ("Plytix", "plytix"),
    ("Syndigo", "syndigo"),
    ("Feedonomics", "feedonomics"),
    ("DataFeedWatch", "datafeedwatch"),
    ("Channable", "channable"),
    ("Productsup", "productsup"),
    ("Skai", "skai"),
    ("Marin Software", "marinsoftware"),
    ("Kenshoo", "kenshoo"),
    ("Adverity", "adverity"),
    ("Supermetrics", "supermetrics"),
    ("Funnel.io", "funnelio"),
    ("TapClicks", "tapclicks"),
    ("Datorama", "datorama"),
    ("Singular", "singular"),
    ("AppsFlyer", "appsflyer"),
    ("Adjust", "adjust"),
    ("Branch", "branch"),
    ("Kochava", "kochava"),
    ("Tenjin", "tenjin"),
    ("Sensor Tower", "sensortower"),
    ("Data.ai", "dataai"),
    ("Apptopia", "apptopia"),
    ("Appfigures", "appfigures"),
    ("App Annie", "appannie"),
    ("Priori Data", "prioridata"),
    ("Gummicube", "gummicube"),
    ("StoreMaven", "storemaven"),
    ("SplitMetrics", "splitmetrics"),
    ("MobileAction", "mobileaction"),
    ("SearchAds.com", "searchads"),
    ("Adikteev", "adikteev"),
    ("Liftoff", "liftoff"),
    ("IronSource", "ironsource"),
    ("Digital Turbine", "digitalturbine"),
    ("Fyber", "fyber"),
    ("Vungle", "vungle"),
    ("AdColony", "adcolony"),
    ("InMobi", "inmobi"),
    ("Moloco", "moloco"),
    ("Smadex", "smadex"),
    ("Jampp", "jampp"),
    ("Remerge", "remerge"),
    ("Appreciate", "appreciate"),
    ("CleverTap", "clevertap"),
    ("Insider", "useinsider"),
    ("MoEngage", "moengage"),
    ("WebEngage", "webengage"),
    ("Netcore Cloud", "netcorecloud"),
    ("Pushwoosh", "pushwoosh"),
    ("Airship", "airship"),
    ("OneSignal", "onesignal"),
    ("Leanplum", "leanplum"),
    ("Localytics", "localytics"),
    ("Mixpanel", "mixpanel"),
    ("Amplitude", "amplitude"),

    # Transportation / Mobility
    ("Waymo", "waymo"),
    ("Cruise", "getcruise"),
    ("Argo AI", "argoai"),
    ("Aurora", "aurora"),
    ("Kodiak Robotics", "kodiak"),
    ("TuSimple", "tusimple"),
    ("Embark Trucks", "embark"),
    ("Gatik", "gatik"),
    ("Nuro", "nuro"),
    ("Motional", "motional"),
    ("May Mobility", "maymobility"),
    ("Optimus Ride", "optimusride"),
    ("Mobileye", "mobileye"),
    ("Continental", "continental"),
    ("Bosch", "bosch"),
    ("Aptiv", "aptiv"),
    ("Magna International", "magna"),
    ("Visteon", "visteon"),
    ("Delphi Technologies", "delphitechnologies"),
    ("BorgWarner", "borgwarner"),
    ("Dana Incorporated", "dana"),
    ("Sensata Technologies", "sensata"),
    ("Modine Manufacturing", "modine"),
    ("Gentherm", "gentherm"),
    ("Superior Industries", "superiorindustries"),
    ("Dorman Products", "dorman"),
    ("Stoneridge", "stoneridge"),
    ("Standard Motor Products", "standardmotor"),
    ("Modine", "modine"),
    ("Uber", "uber"),
    ("Lyft", "lyft"),
    ("DoorDash", "doordash"),
    ("Instacart", "instacart"),
    ("Gopuff", "gopuff"),
    ("Getir", "getir"),
    ("Gorillas", "gorillas"),
    ("Flink", "flink"),
    ("Jokr", "jokr"),
    ("Buyk", "buyk"),
    ("1520", "1520"),
    ("REEF Technology", "reef"),
    ("Darkstore", "darkstore"),
    ("Noissue", "noissue"),
    ("Deliverr", "deliverr"),
    ("ShipBob", "shipbob"),
    ("Shippo", "shippo"),
    ("EasyPost", "easypost"),
    ("Pirateship", "pirateship"),
    ("ShipStation", "shipstation"),
    ("ShipHero", "shiphero"),
    ("Fulfillment by Amazon", "amazon"),
    ("Whiplash", "whiplash"),
    ("Radial", "radial"),
    ("XPO Logistics", "xpo"),
    ("Ryder", "ryder"),
    ("Werner Enterprises", "werner"),
    ("Schneider National", "schneider"),
    ("J.B. Hunt", "jbhunt"),
    ("Old Dominion", "odfl"),
    ("FedEx", "fedex"),
    ("UPS", "ups"),
    ("USPS", "usps"),
    ("DHL", "dhl"),
    ("Amazon Logistics", "amazon"),
    ("Coyote Logistics", "coyotelogistics"),
    ("Echo Global Logistics", "echo"),
    ("C.H. Robinson", "chrobinson"),
    ("Transplace", "transplace"),
    ("project44", "project44"),
    ("FourKites", "fourkites"),
    ("Visibility", "visibility"),
    ("Turvo", "turvo"),
    ("Loadsmart", "loadsmart"),
    ("Convoy", "convoy"),
    ("Transfix", "transfix"),
    ("Emerge", "emerge"),
    ("Leaf Logistics", "leaflogistics"),
    ("Flexe", "flexe"),
    ("STORD", "stord"),
    ("Flowspace", "flowspace"),
    ("Ware2Go", "ware2go"),
    ("Fillogic", "fillogic"),
    ("Locus Robotics", "locusrobotics"),
    ("6 River Systems", "6river"),
    ("inVia Robotics", "inviarobotics"),
    ("Geek+", "geekplus"),
    ("Hai Robotics", "hairobotics"),
    ("Swisslog", "swisslog"),
    ("Knapp", "knapp"),
    ("SSI Schaefer", "ssi-schaefer"),
    ("Dematic", "dematic"),
    ("Vanderlande", "vanderlande"),
    ("Daifuku", "daifuku"),
    ("Muratec", "muratec"),

    # Gaming
    ("Epic Games", "epicgames"),
    ("Unity", "unity"),
    ("Niantic", "nianticlabs"),
    ("Zynga", "zynga"),
    ("King", "king"),
    ("Supercell", "supercell"),
    ("Jam City", "jamcity"),
    ("Glu Mobile", "glumobile"),
    ("Kabam", "kabam"),
    ("Big Fish Games", "bigfishgames"),
    ("WMS Industries", "wms"),
    ("Scientific Games", "scientificgames"),
    ("Aristocrat", "aristocrat"),
    ("IGT", "igt"),
    ("Everi", "everi"),
    ("AGS", "playags"),
    ("Konami Gaming", "konami"),
    ("Bally Technologies", "bally"),
    ("Shuffle Master", "shufflemaster"),
    ("Multimedia Games", "mmgames"),
    ("Incredible Technologies", "itgames"),
    ("Global Cash Access", "globalcash"),
    ("Sightline Payments", "sightline"),
    ("Konami", "konami"),
    ("Playtika", "playtika"),
    ("Ubisoft", "ubisoft"),
    ("EA", "ea"),
    ("2K Games", "2k"),
    ("Blizzard", "blizzard"),
    ("Bungie", "bungie"),
    ("Activision", "activision"),
    ("Bethesda", "bethesda"),
    ("CD Projekt", "cdprojekt"),
    ("Paradox Interactive", "paradoxinteractive"),
    ("Paradox Development Studio", "paradoxdevelopmentstudio"),
    ("Klei Entertainment", "klei"),
    ("Double Fine", "doublefine"),
    ("Insomniac Games", "insomniac"),
    ("Naughty Dog", "naughtydog"),
    ("Santa Monica Studio", "santamonica"),
    ("Guerrilla Games", "guerrilla"),
    ("Sucker Punch", "suckerpunch"),
    ("Bend Studio", "bendstudio"),
    ("Media Molecule", "mediamolecule"),
    ("Firesprite", "firesprite"),
    ("Bluepoint Games", "bluepoint"),
    ("Valkyrie Entertainment", "valkyrie"),
    ("Ballistic Moon", "ballisticmoon"),
    ("XDev", "xdev"),
    ("Turn 10 Studios", "turn10"),
    ("343 Industries", "343industries"),
    ("The Coalition", "thecoalition"),
    ("Playground Games", "playgroundgames"),
    ("Obsidian Entertainment", "obsidian"),
    ("InXile Entertainment", "inxile"),
    ("Double Helix", "doublehelix"),
    ("Rare Ltd", "rare"),
    ("Lionhead Studios", "lionhead"),
    ("Rare", "rare"),
    ("io Interactive", "iointeractive"),
    ("Square Enix", "squareenix"),
    ("Capcom", "capcom"),
    ("Bandai Namco", "bandainamco"),
    ("SEGA", "sega"),
    ("Koei Tecmo", "koeitecmo"),
    ("FromSoftware", "fromsoftware"),
    ("Atlus", "atlus"),
    ("NIS America", "nisamerica"),
    ("NISA Europe", "nisaeurope"),
    ("Xseed Games", "xseed"),
    ("Aksys Games", "aksys"),
    ("Idea Factory", "ideafactory"),
    ("Compile Heart", "compileheart"),
    ("Marvelous", "marvelous"),
    ("GungHo", "gungho"),
    ("Cygames", "cygames"),
    ("DeNA", "dena"),
    ("GREE", "gree"),
    ("mixi", "mixi"),
    ("KLab", "klab"),
    ("COLOPL", "colopl"),
    ("Com2uS", "com2us"),
    ("Netmarble", "netmarble"),
    ("Nexon", "nexon"),
    ("NCSoft", "ncsoft"),
    ("Kakao Games", "kakaogames"),
    ("Pearl Abyss", "pearlabyss"),
    ("Smilegate", "smilegate"),
    ("Krafton", "krafton"),
    ("Wemade", "wemade"),
    ("Com2uS", "com2us"),
    ("4:33 Creative Lab", "433"),
    ("Netease Games", "netease"),
    ("miHoYo", "mihoyo"),
    ("Lilith Games", "lilith"),
    ("IGG", "igg"),
    ("Century Games", "centurygames"),
    ("Yoozoo Games", "yoozoo"),
    ("37 Interactive", "37interactive"),
    ("Perfect World", "perfectworld"),
    ("Shengqu Games", "shengqu"),
    ("iDreamSky", "idreamsky"),
    ("Boyaa Interactive", "boyaa"),

    # EdTech
    ("Khan Academy", "khanacademy"),
    ("Chegg", "chegg"),
    ("Quizlet", "quizlet"),
    ("Kahoot", "kahoot"),
    ("Quizizz", "quizizz"),
    ("Socrative", "socrative"),
    ("Formative", "formative"),
    ("Nearpod", "nearpod"),
    ("Pear Deck", "peardeck"),
    ("Edpuzzle", "edpuzzle"),
    ("Flipgrid", "flipgrid"),
    ("Padlet", "padlet"),
    ("Jamboard", "jamboard"),
    ("Miro", "miro"),
    ("Mural", "mural"),
    ("MIRO", "miro"),
    ("Lucidchart", "lucidchart"),
    ("Creately", "creately"),
    ("Cacoo", "cacoo"),
    ("Gliffy", "gliffy"),
    ("Whimsical", "whimsical"),
    ("FigJam", "figjam"),
    ("Stormboard", "stormboard"),
    ("Conceptboard", "conceptboard"),
    ("Lino", "lino"),
    ("RealtimeBoard", "realtimeboard"),
    ("Mindmeister", "mindmeister"),
    ("MindNode", "mindnode"),
    ("iMindQ", "imindq"),
    ("XMind", "xmind"),
    ("Coggle", "coggle"),
    ("Mindomo", "mindomo"),
    ("Milanote", "milanote"),
    ("Goodnotes", "goodnotes"),
    ("Notability", "gingerlabs"),
    ("OneNote", "onenote"),
    ("Bear", "bear"),
    ("Obsidian", "obsidian"),
    ("Roam Research", "roamresearch"),
    ("Logseq", "logseq"),
    ("Foam", "foam"),
    ("Athens Research", "athensresearch"),
    ("RemNote", "remnote"),
    ("Anki", "anki"),
    ("Brainscape", "brainscape"),
    ("Quizlet", "quizlet"),
    ("Memrise", "memrise"),
    ("Babbel", "babbel"),
    ("Rosetta Stone", "rosettastone"),
    ("Pimsleur", "pimsleur"),
    ("Busuu", "busuu"),
    ("italki", "italki"),
    ("Preply", "preply"),
    ("Cambly", "cambly"),
    ("Verbling", "verbling"),
    ("Lingoda", "lingoda"),
    ("Mango Languages", "mangolanguages"),
    ("Yabla", "yabla"),
    ("FluentU", "fluentu"),
    ("Beelinguapp", "beelinguapp"),
    ("Tandem", "tandem"),
    ("HelloTalk", "hellotalk"),
    ("Speechling", "speechling"),
    ("Pimsleur", "pimsleur"),
    ("Udemy", "udemy"),
    ("Coursera", "coursera"),
    ("edX", "edx"),
    ("LinkedIn Learning", "linkedinlearning"),
    ("Pluralsight", "pluralsight"),
    ("Skillshare", "skillshare"),
    ("Domestika", "domestika"),
    ("CreativeLive", "creativelive"),
    ("Masterclass", "masterclass"),
    ("MindValley", "mindvalley"),
    ("Teachable", "teachable"),
    ("Thinkific", "thinkific"),
    ("Podia", "podia"),
    ("Kajabi", "kajabi"),
    ("Kartra", "kartra"),
    ("ClickFunnels", "clickfunnels"),
    ("Leadpages", "leadpages"),
    ("Unbounce", "unbounce"),
    ("Instapage", "instapage"),

    # Space
    ("SpaceX", "spacex"),
    ("Blue Origin", "blueorigin"),
    ("Virgin Galactic", "virgingalactic"),
    ("Planet Labs", "planet"),
    ("Spire Global", "spire"),
    ("HawkEye 360", "hawkeye360"),
    ("Satellogic", "satellogic"),
    ("Iceye", "iceye"),
    ("Capella Space", "capellaspace"),
    ("Umbra", "umbra"),
    ("BlackSky", "blacksky"),
    ("GeoOptics", "geooptics"),
    ("LeoLabs", "leolabs"),
    ("ExoAnalytic Solutions", "exoanalytic"),
    ("Slingshot Aerospace", "slingshotaerospace"),
    ("LMI Aerospace", "lmiaerospace"),
    ("Sierra Nevada Corporation", "sncorp"),
    ("Northrop Grumman", "northropgrumman"),
    ("Raytheon", "raytheon"),
    ("L3Harris", "l3harris"),
    ("General Dynamics", "generaldynamics"),
    ("BAE Systems", "baesystems"),
    ("Leidos", "leidos"),
    ("SAIC", "saic"),
    ("CACI International", "caci"),
    ("Peraton", "peraton"),
    ("ManTech", "mantech"),
    ("Booz Allen Hamilton", "boozallen"),
    ("Maximus", "maximus"),
    ("ICF", "icf"),
    ("Engility", "engility"),
    ("DLT Solutions", "dlt"),
    ("Noblis", "noblis"),
    ("Mitre", "mitre"),
    ("RAND Corporation", "rand"),
    ("IDA", "ida"),
    ("ANSER", "anser"),
    ("LMI", "lmi"),
    ("Analytic Services", "analyticservices"),
    ("Center for Naval Analyses", "cna"),
    ("Aerospace Corporation", "aerospace"),
    ("System Planning Corporation", "spc"),
    ("Air Force Research Laboratory", "afrl"),
    ("Army Research Laboratory", "arl"),
    ("Naval Research Laboratory", "nrl"),
    ("DARPA", "darpa"),
    ("IARPA", "iarpa"),
    ("In-Q-Tel", "inqtel"),

    # Climate / Energy
    ("Tesla Energy", "tesla"),
    ("Sunrun", "sunrun"),
    ("Sunnova", "sunnova"),
    ("SunPower", "sunpower"),
    ("Vivint Solar", "vivintsolar"),
    ("ADT Solar", "adtsolar"),
    ("Freedom Forever", "freedomforever"),
    ("Pink Energy", "pinkenergy"),
    ("Palmetto Clean Technology", "palmetto"),
    ("Mosaic", "joinmosaic"),
    ("Dividend Finance", "dividendfinance"),
    ("Loanpal", "loanpal"),
    ("GoodLeap", "goodleap"),
    ("Enfin", "enfin"),
    ("Metrus Energy", "metrusenergy"),
    ("Wunder Capital", "wundercapital"),
    ("Clean Capital", "cleancapital"),
    ("CleanChoice Energy", "cleanchoiceenergy"),
    ("Arcadia", "arcadia"),
    ("Arcadia Power", "arcadiapower"),
    ("OhmConnect", "ohmconnect"),
    ("Recurve", "recurve"),
    ("Leap", "leapfactor"),
    ("AutoGrid", "autogrid"),
    ("Stem Inc", "stem"),
    ("Fluence", "fluence"),
    ("ESS Tech", "essinc"),
    ("Form Energy", "formenergy"),
    ("Ambri", "ambri"),
    ("Primus Power", "primuspower"),
    ("EnerVault", "enervault"),
    ("Aquion Energy", "aquionenergy"),
    ("EnerSys", "enersys"),
    ("Clarios", "clarios"),
    ("Enovix", "enovix"),
    ("Solid Power", "solidpower"),
    ("QuantumScape", "quantumscape"),
    ("SES AI", "sesai"),
    ("Sila Nanotechnologies", "silanano"),
    ("Amprius", "amprius"),
    ("Enevate", "enevate"),
    ("Factorial Energy", "factorialenergy"),
    ("StoreDot", "storedot"),
    ("SilaNanotechnologies", "silanano"),
    ("Group14 Technologies", "group14"),
    ("Nanograde", "nanograde"),
    ("Electrovaya", "electrovaya"),
    ("Alevo Group", "alevo"),
    ("EnergyHub", "energyhub"),
    ("Span.io", "span"),
    ("Sense", "sense"),
    ("Bidgee", "bidgee"),
    ("Uplight", "uplight"),
    ("Itron", "itron"),
    ("Landis+Gyr", "landisgyr"),
    ("Xylem", "xylem"),
    ("Evoqua Water Technologies", "evoqua"),
    ("Veolia", "veolia"),
    ("Suez", "suez"),
    ("Xylem", "xylem"),
    ("Grundfos", "grundfos"),
    ("Xylem", "xylem"),
    ("Watts Water Technologies", "watts"),
    ("Rexnord", "rexnord"),
    ("Mueller Water Products", "muellerwater"),
    ("Badger Meter", "badgermeter"),
    ("Core & Main", "coreandmain"),
    ("Ferguson", "ferguson"),
    ("Watsco", "watsco"),
    ("Lennox International", "lennox"),
    ("Carrier Global", "carrier"),
    ("Trane Technologies", "trane"),
    ("Johnson Controls", "johnsoncontrols"),
    ("Emerson Electric", "emerson"),
    ("Honeywell", "honeywell"),
    ("Siemens", "siemens"),
    ("ABB", "abb"),
    ("Schneider Electric", "schneider"),
    ("Eaton", "eaton"),
    ("Rockwell Automation", "rockwellautomation"),
    ("Beckett Industrial", "beckett"),

    # Media / Entertainment
    ("Netflix", "netflix"),
    ("Hulu", "hulu"),
    ("Disney+", "disney"),
    ("HBO Max", "hbo"),
    ("Peacock", "peacock"),
    ("Paramount+", "paramount"),
    ("Apple TV+", "apple"),
    ("Amazon Prime Video", "amazon"),
    ("Tubi", "tubi"),
    ("Pluto TV", "plutotv"),
    ("Xumo", "xumo"),
    ("Crackle", "crackle"),
    ("Vudu", "vudu"),
    ("FandangoNow", "fandangonow"),
    ("Fandango", "fandango"),
    ("Atom Tickets", "atomtickets"),
    ("MoviePass", "moviepass"),
    ("Sinemia", "sinemia"),
    ("AMC Theatres", "amctheatres"),
    ("Regal Cinemas", "regal"),
    ("Cinemark", "cinemark"),
    ("Alamo Drafthouse", "alamodrafthouse"),
    ("Landmark Theatres", "landmarktheatres"),
    ("Drafthouse Films", "drafthousetfilms"),
    ("A24", "a24"),
    ("Neon", "neon"),
    ("IFC Films", "ifc"),
    ("Oscilloscope", "oscilloscope"),
    ("Magnolia Pictures", "magnoliapictures"),
    ("Bleecker Street", "bleeckerstreet"),
    ("Greenwich Entertainment", "greenwich"),
    ("Music Box Films", "musicboxfilms"),
    ("Samuel Goldwyn Films", "goldwyn"),
    ("Vertical Entertainment", "vertical"),
    ("Gravitas Ventures", "gravitas"),
    ("Parade Deck Films", "paradedeck"),
    ("Raven Banner Entertainment", "ravenbanner"),
    ("Uncork'd Entertainment", "uncorkd"),
    ("Freestyle Digital Media", "freestylemedia"),
    ("Indie Rights", "indierights"),
    ("Terror Films", "terrorfilms"),
    ("Shout! Factory", "shout"),
    ("Mill Creek Entertainment", "millcreek"),
    ("Olive Films", "olivefilms"),
    ("Kino Lorber", "kinolorber"),
    ("Criterion Collection", "criterion"),
    ("Twilight Time", "twilighttime"),
    ("Arrow Video", "arrowvideo"),
    ("Severin Films", "severin"),
    ("Vinegar Syndrome", "vinegarsyndrome"),
    ("Synapse Films", "synapse"),
    ("Code Red", "coderedfilms"),
    ("Full Moon Features", "fullmoon"),
    ("Troma Entertainment", "troma"),
    ("Something Weird Video", "somethingweird"),
    ("Something Weird", "somethingweird"),

    # HR / Recruiting Tech
    ("Workday", "workday"),
    ("iCIMS", "icims"),
    ("Taleo", "taleo"),
    ("Jobvite", "jobvite"),
    ("SmartRecruiters", "smartrecruiters"),
    ("Lever", "lever"),
    ("Greenhouse", "greenhouse"),
    ("Ashby", "ashby"),
    ("Recruitee", "recruitee"),
    ("Workable", "workable"),
    ("Breezy HR", "breezyhr"),
    ("JazzHR", "jazzhr"),
    ("Pinpoint", "pinpointhq"),
    ("Teamtailor", "teamtailor"),
    ("Personio", "personio"),
    ("Recruitly", "recruitly"),
    ("TalentLyft", "talentlyft"),
    ("TalentReef", "talentreef"),
    ("Applied", "beapplied"),
    ("Longlister", "longlister"),
    ("Tribepad", "tribepad"),
    ("Talenthub", "talenthub"),
    ("Comeet", "comeet"),
    ("Zoho Recruit", "zohorecruit"),
    ("Freshteam", "freshteam"),
    ("BambooHR", "bamboohr"),
    ("HiBob", "hibob"),
    ("Lattice", "lattice"),
    ("Leapsome", "leapsome"),
    ("15Five", "15five"),
    ("Betterworks", "betterworks"),
    ("Reflektive", "reflektive"),
    ("Engagedly", "engagedly"),
    ("Trakstar", "trakstar"),
    ("Reviewsnap", "reviewsnap"),
    ("PerformYard", "performyard"),
    ("ClearCompany", "clearcompany"),
    ("Cornerstone OnDemand", "cornerstoneondemand"),
    ("Saba Software", "saba"),
    ("SumTotal Systems", "sumtotal"),
    ("Halogen Software", "halogen"),
    ("Emplify", "emplify"),
    ("Glint", "glint"),
    ("Peakon", "peakon"),
    ("Culture Amp", "cultureamp"),
    ("Qualtrics Employee Experience", "qualtrics"),
    ("TINYpulse", "tinypulse"),
    ("Officevibe", "officevibe"),
    ("SurveyMonkey Engage", "surveymonkey"),
    ("SurveyMonkey", "surveymonkey"),
    ("Typeform", "typeform"),
    ("Alchemer", "alchemer"),
    ("SoGoSurvey", "sogosurvey"),
    ("Formstack", "formstack"),
    ("JotForm", "jotform"),
    ("Google Forms", "google"),
    ("Microsoft Forms", "microsoft"),
    ("Cognito Forms", "cognitoforms"),
    ("Wufoo", "wufoo"),
    ("123FormBuilder", "123formbuilder"),
    ("FormAssembly", "formassembly"),
    ("Cvent", "cvent"),
    ("Splash", "splashat"),
    ("Eventbrite", "eventbrite"),
    ("Bizzabo", "bizzabo"),
    ("Whova", "whova"),
    ("Hopin", "hopin"),
    ("Airmeet", "airmeet"),
    ("Run The World", "runtheworld"),
    ("Bevy", "bevy"),
    ("Meetup", "meetup"),
    ("Eventable", "eventable"),
    ("Sched", "sched"),
    ("Swoogo", "swoogo"),
    ("Stova", "stova"),
    ("EventMobi", "eventmobi"),
    ("DoubleDutch", "doubledutch"),
    ("CrowdCompass", "crowdcompass"),

    # Legal Tech
    ("Clio", "clio"),
    ("LexisNexis", "lexisnexis"),
    ("Westlaw", "westlaw"),
    ("Fastcase", "fastcase"),
    ("Ravel Law", "ravellaw"),
    ("Judicata", "judicata"),
    ("Ross Intelligence", "rossintelligence"),
    ("Luminance", "luminance"),
    ("Kira Systems", "kirasystems"),
    ("Seal Software", "seal"),
    ("LegalSifter", "legalsifter"),
    ("Ironclad", "ironcladapp"),
    ("Conga", "conga"),
    ("ContractPodAi", "contractpodai"),
    ("Icertis", "icertis"),
    ("Agiloft", "agiloft"),
    ("Lexion", "lexion"),
    ("Pactum AI", "pactum"),
    ("LexCheck", "lexcheck"),
    ("Evisort", "evisort"),
    ("Summize", "summize"),
    ("Definely", "definely"),
    ("Legalese", "legalese"),
    ("Avvoka", "avvoka"),
    ("Docusign", "docusign"),
    ("HelloSign", "hellosign"),
    ("PandaDoc", "pandadoc"),
    ("Nitro", "nitro"),
    ("Proposify", "proposify"),
    ("Qwilr", "qwilr"),
    ("Better Proposals", "betterproposals"),
    ("Bidsketch", "bidsketch"),
    ("Nusii", "nusii"),
    ("Loopio", "loopio"),
    ("Responsive", "responsive"),
    ("RFPIO", "rfpio"),
    ("Ombud", "ombud"),
    ("Qvidian", "qvidian"),
    ("Xait", "xait"),
    ("Expedience Software", "expedience"),
    ("Proposify", "proaify"),

    # Real Estate / PropTech
    ("Zillow", "zillow"),
    ("Redfin", "redfin"),
    ("Opendoor", "opendoor"),
    ("Offerpad", "offerpad"),
    ("Knock", "knock"),
    ("Orchard", "orchard"),
    ("Flyhomes", "flyhomes"),
    ("Ribbon", "ribbon"),
    ("Homeward", "homeward"),
    ("Divvy Homes", "divvyhomes"),
    ("ZeroDown", "zerodown"),
    ("Point", "pointdigital"),
    ("Hometap", "hometap"),
    ("Unlock", "unlock"),
    ("Unison", "unison"),
    ("Noah", "noah"),
    ("EasyKnock", "easyknock"),
    ("Sell2Rent", "sell2rent"),
    ("Truehold", "truehold"),
    ("Arrived Homes", "arrived"),
    ("Roots", "investwithroots"),
    ("RealtyMogul", "realtymogul"),
    ("Streitwise", "streitwise"),
    ("DiversyFund", "diversyfund"),
    ("HoneyBricks", "honeybricks"),
    ("Lofty AI", "loftyai"),
    ("Vesto", "vesto"),
    ("Groundfloor", "groundfloor"),
    ("PeerStreet", "peerstreet"),
    ("RealtyShares", "realtyshares"),
    ("AlphaFlow", "alphaflow"),
    ("EquityMultiple", "equitymultiple"),
    ("CrowdStreet", "crowdstreet"),
    ("Origin Investments", "origininvestments"),
    ("Juniper Square", "junipersquare"),
    ("Yardi", "yardi"),
    ("RealPage", "realpage"),
    ("AppFolio", "appfolio"),
    ("Buildium", "buildium"),
    ("Propertyware", "propertyware"),
    ("Rentec Direct", "rentecdirect"),
    ("Landlord Studio", "landlordstudio"),
    ("Cozy", "cozy"),
    ("TenantCloud", "tenantcloud"),
    ("Avail", "avail"),
    ("Renters Warehouse", "renterswarehouse"),
    ("Vacasa", "vacasa"),
    ("Evolve Vacation Rental", "evolve"),
    ("TurnKey Vacation Rentals", "turnkey"),
    ("Sonder", "sonder"),
    ("Lyric", "lyric"),
    ("Domio", "domio"),
    ("WhyHotel", "whyhotel"),
    ("Frontdesk", "frontdesk"),
    ("Migo", "migostays"),
    ("Selfoss", "selfoss"),
    ("Kasa Living", "kasa"),
    ("June Homes", "junehomes"),
    ("Bungalow", "bungalow"),
    ("WeLive", "welive"),
    ("Common", "common"),
    ("Outpost Club", "outpostclub"),
    ("Quarters", "quarters"),
    ("The Guild", "theguild"),
    ("Starcity", "starcity"),
    ("Ollie", "ollie"),
    ("Kin", "kin"),
    ("Habyt", "habyt"),
    ("Hmlet", "hmlet"),
    ("lyf", "lyf"),
    ("Tribe Co-Living", "tribe"),
    ("Urban Rest", "urbanrest"),
    ("Sonder", "sonder"),

    # Food / Restaurant Tech
    ("Toast", "toasttab"),
    ("Olo", "olo"),
    ("Lunchbox", "lunchbox"),
    ("Tillster", "tillster"),
    ("Paytronix", "paytronix"),
    ("Punchh", "punchh"),
    ("LoyaltyPlant", "loyaltyplant"),
    ("Fishbowl", "fishbowl"),
    ("Popmenu", "popmenu"),
    ("OpenTable", "opentable"),
    ("Resy", "resy"),
    ("Yelp", "yelp"),
    ("Zomato", "zomato"),
    ("Swiggy", "swiggy"),
    ("Deliveroo", "deliveroo"),
    ("Uber Eats", "uber"),
    ("DoorDash", "doordash"),
    ("Grubhub", "grubhub"),
    ("Caviar", "trycaviar"),
    ("Seamless", "seamless"),
    ("Postmates", "postmates"),
    ("Slice", "slicelife"),
    ("Menufy", "menufy"),
    ("Beyond Menu", "beyondmenu"),
    ("Allset", "allset"),
    ("ChowNow", "chownow"),
    ("Bopple", "bopple"),
    ("Flipdish", "flipdish"),
    ("Yumbi", "yumbi"),
    ("Presto Automation", "presto"),
    ("Miso Robotics", "misorobotics"),
    ("Bear Robotics", "bearrobotics"),
    ("Richtech Robotics", "richtechrobotics"),
    ("Aethon", "aethon"),
    ("Keenon Robotics", "keenonrobotics"),
    ("Aidea", "aidea"),
    ("Covariant", "covariant"),
    ("Nymble", "nymble"),
    ("Moley Robotics", "moley"),
    ("Samsung Food", "samsungfood"),
    ("Whisk", "whisk"),
    ("Mealime", "mealime"),
    ("Paprika Recipe Manager", "paprika"),
    ("Yummly", "yummly"),
    ("Tasty", "tasty"),
    ("SideChef", "sidechef"),
    ("Cookpad", "cookpad"),
    ("BigOven", "bigoven"),
    ("Allrecipes", "allrecipes"),
    ("Epicurious", "epicurious"),
    ("Food Network", "foodnetwork"),
    ("Serious Eats", "seriouseats"),
    ("The Kitchn", "thekitchn"),
    ("Bon Appétit", "bonappetit"),
    ("Food52", "food52"),
    ("Feedfeed", "feedfeed"),
    ("Tastemade", "tastemade"),
    ("Delish", "delish"),
    ("Chowhound", "chowhound"),

    # Robotics / Hardware
    ("Boston Dynamics", "bostondynamics"),
    ("iRobot", "irobot"),
    ("Neato Robotics", "neatorobotics"),
    ("Ecovacs", "ecovacs"),
    ("Dyson", "dyson"),
    ("SharkNinja", "sharkninja"),
    ("iLife", "ilife"),
    ("Xiaomi Roborock", "roborock"),
    ("Dreame", "dreame"),
    ("Viomi", "viomi"),
    ("360 Robot Vacuum", "360vacuum"),
    ("Eufy", "eufy"),
    ("Narwal", "narwal"),
    ("Trifo", "trifo"),
    ("Hobot", "hobot"),
    ("Maidbot", "maidbot"),
    ("Taski", "taski"),
    ("Diversey", "diversey"),
    ("Tennant", "tennant"),
    ("Nilfisk", "nilfisk"),
    ("Kärcher", "karcher"),
    ("Hako", "hako"),
    ("Comac", "comac"),
    ("Avidbots", "avidbots"),
    ("Tailos", "tailos"),
    ("Softbank Robotics", "softbankrobotics"),
    ("Pepper the Robot", "pepper"),
    ("Double Robotics", "doublerobotics"),
    ("OhmniLabs", "ohmnilabs"),
    ("Suitable Technologies", "suitabletech"),
    ("Beam", "beam"),
    ("Anki", "anki"),
    ("Cozmo", "cozmo"),
    ("Sphero", "sphero"),
    ("Leka", "leka"),
    ("Miko", "miko"),
    ("Embodied", "embodied"),
    ("ROYBI Robot", "roybi"),
    ("Wonder Workshop", "wonderworkshop"),
    ("RoboKind", "robokind"),
    ("LLVision", "llvision"),
    ("Hanson Robotics", "hansonrobotics"),
    ("Aldebaran", "aldebaran"),
    ("Universal Robots", "universalrobots"),
    ("KUKA", "kuka"),
    ("FANUC", "fanuc"),
    ("ABB Robotics", "abb"),
    ("Yaskawa", "yaskawa"),
    ("Stäubli", "staubli"),
    ("Epson Robots", "epsonrobots"),
    ("Kawasaki Robotics", "kawasakirobotics"),
    ("Nachi", "nachi"),
    ("Mitsubishi Electric", "mitsubishielectric"),
    ("Denso Robotics", "densorobotics"),
    ("Omron Automation", "omron"),
    ("Bosch Rexroth", "boschrexroth"),
    ("Parker Hannifin", "parker"),
    ("Festo", "festo"),
    ("SMC Corporation", "smc"),
    ("Keyence", "keyence"),
    ("Cognex", "cognex"),
    ("Basler", "baslerweb"),
    ("FLIR Systems", "flir"),
    ("Teledyne", "teledyne"),
    ("Zebra Technologies", "zebra"),
    ("Honeywell Robotics", "honeywell"),
    ("Sick AG", "sick"),
    ("Banner Engineering", "bannerengineering"),
    ("Balluff", "balluff"),
    ("Turck", "turck"),
    ("IFM Electronic", "ifm"),
    ("Pepperl+Fuchs", "pepperl-fuchs"),

    # Additional well-known tech companies
    ("Salesforce", "salesforce"),
    ("Oracle", "oracle"),
    ("SAP", "sap"),
    ("IBM", "ibm"),
    ("Microsoft", "microsoft"),
    ("Google", "google"),
    ("Meta", "meta"),
    ("Apple", "apple"),
    ("Amazon", "amazon"),
    ("Twitter", "twitter"),
    ("LinkedIn", "linkedin"),
    ("Snap", "snap"),
    ("TikTok", "tiktok"),
    ("Bytedance", "bytedance"),
    ("Uber", "uber"),
    ("Airbnb", "airbnb"),
    ("Netflix", "netflix"),
    ("Spotify", "spotify"),
    ("Slack", "slack"),
    ("Zoom", "zoom"),
    ("Dropbox", "dropbox"),
    ("Box", "box"),
    ("Atlassian", "atlassian"),
    ("GitHub", "github"),
    ("GitLab", "gitlab"),
    ("Shopify", "shopify"),
    ("Square", "square"),
    ("Stripe", "stripe"),
    ("PayPal", "paypal"),
    ("Intuit", "intuit"),
    ("Workday", "workday"),
    ("ServiceNow", "servicenow"),
    ("Splunk", "splunk"),
    ("Elastic", "elastic"),
    ("MongoDB", "mongodb"),
    ("Snowflake", "snowflake"),
    ("Databricks", "databricks"),
    ("Twilio", "twilio"),
    ("SendGrid", "sendgrid"),
    ("Mailchimp", "mailchimp"),
    ("HubSpot", "hubspot"),
    ("Zendesk", "zendesk"),
    ("Intercom", "intercom"),
    ("Drift", "drift"),
    ("Gainsight", "gainsight"),
    ("Totango", "totango"),
    ("ChurnZero", "churnzero"),
    ("Catalyst", "catalyst"),
    ("Planhat", "planhat"),
    ("ClientSuccess", "clientsuccess"),
    ("Vitally", "vitally"),
    ("Arrows", "arrows"),
    ("Rocketlane", "rocketlane"),
    ("Pendo", "pendo"),
    ("WalkMe", "walkme"),
    ("Appcues", "appcues"),
    ("Chameleon", "chameleon"),
    ("UserGuiding", "userguiding"),
    ("Interactly", "interactly"),
    ("Userlane", "userlane"),
    ("Stonly", "stonly"),
    ("Inline Manual", "inlinemanual"),
    ("Nickelled", "nickelled"),
    ("Userpilot", "userpilot"),
    ("Helppier", "helppier"),
    ("Hopscotch", "hopscotch"),
    ("Whatfix", "whatfix"),
    ("Intellum", "intellum"),
    ("Lessonly", "lessonly"),
    ("Bridge", "bridgeapp"),
    ("Docebo", "docebo"),
    ("Absorb LMS", "absorblms"),
    ("TalentLMS", "talentlms"),
    ("iSpring", "ispring"),
    ("Looop", "looop"),
    ("Zavvy", "zavvy"),
    ("EdCast", "edcast"),
    ("Degreed", "degreed"),
    ("360Learning", "360learning"),
    ("NovoEd", "novoed"),
    ("Percipio", "percipio"),
    ("Axonify", "axonify"),
    ("Arist", "arist"),
    ("EduMe", "edume"),
    ("Coassemble", "coassemble"),
    ("SC Training", "sctraining"),
    ("Learnerbly", "learnerbly"),
    ("GoodHabitz", "goodhabitz"),
    ("OpenSesame", "opensesame"),
    ("Skillsoft", "skillsoft"),
    ("Pluralsight", "pluralsight"),
    ("O'Reilly", "oreilly"),
    ("ACM Learning", "acm"),
    ("Codecademy", "codecademy"),
    ("Treehouse", "treehouse"),
    ("Frontend Masters", "frontendmasters"),
    ("Egghead", "egghead"),
    ("Laracasts", "laracasts"),
    ("Wes Bos", "wesbos"),
    ("LevelUpTuts", "leveluptuts"),
    ("Traversy Media", "traversy"),
    ("The Odin Project", "theodinproject"),
    ("freeCodeCamp", "freecodecamp"),
    ("The Gym Group", "thegymgroup"),
    ("Pure Gym", "puregym"),
    ("Anytime Fitness", "anytimefitness"),
    ("Planet Fitness", "planetfitness"),
    ("24 Hour Fitness", "24hourfitness"),
    ("Equinox", "equinox"),
    ("SoulCycle", "soulcycle"),
    ("ClassPass", "classpass"),
    ("Mindbody", "mindbody"),
    ("Wellhub", "wellhub"),
    ("Virgin Active", "virginactive"),
    ("David Lloyd", "davidlloyd"),
    ("Fitness First", "fitnessfirst"),
    ("Gold's Gym", "goldsgym"),
    ("LA Fitness", "lafitness"),
    ("Life Time Fitness", "lifetime"),
    ("F45 Training", "f45training"),
    ("Barry's", "barrys"),
    ("Orangetheory", "orangetheory"),
    ("Rumble Boxing", "rumble"),
    ("Solidcore", "solidcore"),
    ("Peloton", "peloton"),
    ("Mirror", "mirror"),
    ("Tonal", "tonal"),
    ("Tempo", "tempo"),
    ("Hydrow", "hydrow"),
    ("NordicTrack", "nordictrack"),
    ("Bowflex", "bowflex"),
    ("Theragun", "theragun"),
    ("Hyperice", "hyperice"),
    ("Whoop", "whoop"),
    ("Oura", "oura"),
    ("Garmin", "garmin"),
    ("Fitbit", "fitbit"),
    ("Polar", "polar"),
    ("Suunto", "suunto"),
    ("Coros", "coros"),
    ("Wahoo Fitness", "wahoo"),
    ("Zwift", "zwift"),
    ("TrainerRoad", "trainerroad"),
    ("Strava", "strava"),
    ("Komoot", "komoot"),
    ("AllTrails", "alltrails"),
    ("Peakbagger", "peakbagger"),
    ("Hiking Project", "hikingproject"),
    ("Mountain Project", "mountainproject"),
    ("Gaia GPS", "gaiagps"),
    ("CalTopo", "caltopo"),
    ("Fatmap", "fatmap"),
    ("PeakVisor", "peakvisor"),
    ("Ski Tracks", "skitracks"),
    ("Slopes", "slopes"),
    ("Snocru", "snocru"),
    ("Alpine Replay", "alpinereplay"),
    ("Glympse", "glympse"),

    # Additional notable startups / scaleups
    ("Airtable", "airtable"),
    ("Monday.com", "mondaydotcom"),
    ("Smartsheet", "smartsheet"),
    ("Basecamp", "basecamp"),
    ("Trello", "trello"),
    ("Asana", "asana"),
    ("ClickUp", "clickup"),
    ("Wrike", "wrike"),
    ("Teamwork", "teamwork"),
    ("ProofHub", "proofhub"),
    ("Hive", "hive"),
    ("Nifty", "nifty"),
    ("Podio", "podio"),
    ("Redbooth", "redbooth"),
    ("Zoho Projects", "zohoprojects"),
    ("LiquidPlanner", "liquidplanner"),
    ("Mavenlink", "mavenlink"),
    ("Teamgantt", "teamgantt"),
    ("Tom's Planner", "tomsplanner"),
    ("Instagantt", "instagantt"),
    ("GanttPRO", "ganttpro"),
    ("Paymo", "paymo"),
    ("Hubstaff", "hubstaff"),
    ("Toggl", "toggl"),
    ("Harvest", "harvest"),
    ("TimeCamp", "timecamp"),
    ("Clockify", "clockify"),
    ("Everhour", "everhour"),
    ("Timely", "timely"),
    ("RescueTime", "rescuetime"),
    ("Timing", "timing"),
    ("Timing", "timing"),
    ("DeskTime", "desktime"),
    ("Time Doctor", "timedoctor"),
    ("Teramind", "teramind"),
    ("ActivTrak", "activtrak"),
    ("InterGuard", "interguard"),
    ("Veriato", "veriato"),
    ("CurrentWare", "currentware"),
    ("Controlio", "controlio"),
    ("Awareness Technologies", "awareness"),
    ("SpectorSoft", "spectorsoft"),
    ("NetVizor", "netvizor"),
    ("SentryPC", "sentrypc"),
    ("WebWatcher", "webwatcher"),
    ("Bark", "bark"),
    ("Qustodio", "qustodio"),
    ("Circle", "circle"),
    ("Disney Circle", "circle"),
    ("Family Link", "familylink"),
    ("Screen Time", "screentime"),
    ("OurPact", "ourpact"),
    ("Boomerang Parental Control", "boomerang"),
    ("Mobicip", "mobicip"),
    ("Norton Family", "norton"),
    ("Kaspersky Safe Kids", "kaspersky"),
    ("ESET Parental Control", "eset"),
    ("Bitdefender Parental Control", "bitdefender"),
    ("Trend Micro Family", "trendmicro"),
    ("McAfee Safe Family", "mcafee"),
    ("F-Secure SAFE", "fsecure"),
    ("Avast Family Shield", "avast"),
    ("AVG Family", "avg"),
    ("Lookout", "lookout"),
    ("Zimperium", "zimperium"),
    ("Pradeo", "pradeo"),
    ("Appthority", "appthority"),
    ("Wandera", "wandera"),
    ("Better Mobile Security", "bettermobile"),
    ("MobileIron", "mobileiron"),
    ("Jamf", "jamf"),
    ("Addigy", "addigy"),
    ("Mosyle", "mosyle"),
    ("Kandji", "kandji"),
    ("Meraki MDM", "meraki"),
    ("VMware Workspace ONE", "vmware"),
    ("Citrix Endpoint Management", "citrix"),
    ("Microsoft Intune", "microsoft"),
    ("BlackBerry UEM", "blackberry"),
    ("IBM MaaS360", "ibm"),
    ("SOTI MobiControl", "soti"),
    ("Ivanti", "ivanti"),
    ("ManageEngine Mobile Device Manager", "manageengine"),
    ("Hexnode", "hexnode"),
    ("Scalefusion", "scalefusion"),
    ("42Gears", "42gears"),
    ("Miradore", "miradore"),
    ("Sophos Mobile", "sophos"),
    ("Symantec Endpoint", "symantec"),
    ("CylancePROTECT", "cylance"),
    ("Carbon Black", "carbonblack"),
    ("Malwarebytes", "malwarebytes"),
    ("Webroot", "webroot"),
    ("Emsisoft", "emsisoft"),
    ("Panda Security", "pandasecurity"),
    ("G Data", "gdatasoftware"),
    ("Avira", "avira"),
    ("Total Defense", "totaldefense"),
    ("Comodo", "comodo"),
    ("PC Matic", "pcmatic"),
    ("Immunet", "immunet"),
    ("Clam AV", "clamav"),
    ("HerdProtect", "herdprotect"),
    ("Reason Core Security", "reasonsecurity"),
    ("GridinSoft Anti-Malware", "gridinsoft"),
    ("UnHackMe", "unhackme"),
    ("Spybot", "safer-networking"),
    ("AdwCleaner", "malwarebytes"),
    ("SuperAntiSpyware", "superantispyware"),
    ("TotalAV", "totalav"),
    ("Scanguard", "scanguard"),
    ("iolo System Mechanic", "iolo"),
    ("AVG TuneUp", "avg"),
    ("CCleaner", "ccleaner"),
    ("Piriform", "piriform"),
    ("IObit Advanced SystemCare", "iobit"),
    ("Glary Utilities", "glarysoft"),
    ("Wise Care 365", "wisecleaner"),
    ("SlimCleaner", "slimware"),
    ("Auslogics BoostSpeed", "auslogics"),
    ("Uniblue", "uniblue"),
    ("Reimage", "reimage"),
    ("Restoro", "restoro"),
    ("Advanced System Repair", "systweak"),
    ("Systweak", "systweak"),
]

JOBS_API = "https://boards-api.greenhouse.io/v1/boards/{}/jobs"
BOARD_API = "https://boards-api.greenhouse.io/v1/boards/{}"


def slug_to_name(slug: str) -> str:
    """Best-effort human name from a slug when no other source is available."""
    s = re.sub(r"[-_]", " ", slug)
    s = re.sub(r"([a-z])([A-Z])", r"\1 \2", s)
    return s.title()


async def check_slug(
    session: aiohttp.ClientSession,
    hint_name: str,
    slug: str,
    sem: asyncio.Semaphore,
    resolve_name: bool = False,
) -> Optional[dict]:
    if slug in EXISTING_SLUGS:
        return None
    async with sem:
        try:
            async with session.get(
                JOBS_API.format(slug), timeout=aiohttp.ClientTimeout(total=12)
            ) as resp:
                if resp.status != 200:
                    return None
                data = await resp.json(content_type=None)
                jobs = data.get("meta", {}).get("total") or len(data.get("jobs", []))
                name = hint_name
                # When we only have a slug, try the board-info endpoint for a real name
                if resolve_name:
                    try:
                        async with session.get(
                            BOARD_API.format(slug),
                            timeout=aiohttp.ClientTimeout(total=8),
                        ) as br:
                            if br.status == 200:
                                bd = await br.json(content_type=None)
                                name = bd.get("name") or name
                    except Exception:
                        pass
                return {"name": name, "slug": slug, "jobs": jobs}
        except Exception:
            pass
    return None


async def discover(candidates: list, concurrency: int, resolve_name: bool):
    sem = asyncio.Semaphore(concurrency)
    connector = aiohttp.TCPConnector(limit=concurrency, ssl=False)
    async with aiohttp.ClientSession(connector=connector) as session:
        tasks = [
            check_slug(session, name, slug, sem, resolve_name)
            for name, slug in candidates
        ]
        results = []
        done = 0
        total = len(tasks)
        for coro in asyncio.as_completed(tasks):
            result = await coro
            done += 1
            if result:
                results.append(result)
                print(f"  ✓ {result['name']} ({result['slug']}) — {result['jobs']} jobs")
            if done % 100 == 0:
                print(f"[{done}/{total}] checked, {len(results)} found so far...")
        return results


def main():
    parser = argparse.ArgumentParser(description="Discover Greenhouse companies")
    parser.add_argument("--from-file", type=str, default=None,
                        help="JSON file with a list of slugs (e.g. from Feashliaa dataset)")
    parser.add_argument("--min-jobs", type=int, default=1, help="Min jobs to include (default: 1)")
    parser.add_argument("--concurrency", type=int, default=50, help="Concurrent requests (default: 50)")
    parser.add_argument("--output", type=str, default=None, help="Save results to CSV file")
    parser.add_argument("--no-resolve-name", action="store_true",
                        help="Skip the extra board-info call to resolve company names (faster)")
    args = parser.parse_args()

    if args.from_file:
        with open(args.from_file) as f:
            raw_slugs = json.load(f)
        # Filter out already-tracked and obvious garbage
        candidates = [
            (slug_to_name(s), s)
            for s in raw_slugs
            if s not in EXISTING_SLUGS and len(s) >= 3 and not re.match(r"^\d+$", s)
        ]
        resolve_name = not args.no_resolve_name
        print(f"Loaded {len(raw_slugs)} slugs from {args.from_file}")
        print(f"After filtering known companies: {len(candidates)} to check")
    else:
        candidates = [(name, slug) for name, slug in SEED if slug not in EXISTING_SLUGS]
        resolve_name = False
        print(f"Using built-in seed list: {len(candidates)} candidates")

    print(f"Skipping {len(EXISTING_SLUGS)} already-tracked companies.")
    print(f"Concurrency: {args.concurrency}, resolve names: {resolve_name}\n")

    start = time.time()
    results = asyncio.run(discover(candidates, args.concurrency, resolve_name))
    elapsed = time.time() - start

    confirmed = [r for r in results if r["jobs"] >= args.min_jobs]
    confirmed.sort(key=lambda x: x["jobs"], reverse=True)

    print(f"\n{'='*60}")
    print(f"Found {len(confirmed)} new Greenhouse companies (≥{args.min_jobs} jobs) in {elapsed:.1f}s\n")

    for r in confirmed:
        print(f"  {r['name']:<40} {r['slug']:<30} {r['jobs']:>5} jobs")

    if args.output:
        with open(args.output, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["name", "slug", "jobs"])
            writer.writeheader()
            writer.writerows(confirmed)
        print(f"\nSaved to {args.output}")

    print(f"\ncompanies.py snippet:")
    print("-" * 60)
    for r in confirmed:
        slug = r["slug"]
        name = r["name"]
        print(f'    {{"slug": "{slug}", "name": "{name}", "ats": "greenhouse", "industry": "TBD"}},')


if __name__ == "__main__":
    main()
