"""add company profile fields

Revision ID: 1490a77b3313
Revises: 5a29360164c3
Create Date: 2026-06-05 01:50:01.155477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1490a77b3313'
down_revision = '5a29360164c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('founded_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('valuation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('valuation')
        batch_op.drop_column('company_type')
        batch_op.drop_column('founded_year')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
