"""add role_candidates table

Revision ID: 45e6ecc7a4e7
Revises: bc9471b18267
Create Date: 2026-05-10 02:53:34.955029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e6ecc7a4e7'
down_revision = 'bc9471b18267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sa.String(length=500), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=True),
    sa.Column('company_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mapped_role_id', sa.Integer(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapped_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_candidates_raw_title'), ['raw_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_candidates_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_role_candidates_raw_title'))

    op.drop_table('role_candidates')
    # ### end Alembic commands ###
