"""Initial schema

Revision ID: 56684aa7ff4c
Revises: 
Create Date: 2026-01-07 05:26:57.389775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56684aa7ff4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('ats_type', sa.String(length=50), nullable=True),
    sa.Column('greenhouse_slug', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scrape_enabled', sa.Boolean(), nullable=True),
    sa.Column('scrape_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('total_jobs_scraped', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('job_family', sa.String(length=100), nullable=True),
    sa.Column('total_active_jobs', sa.Integer(), nullable=True),
    sa.Column('avg_salary_min', sa.Integer(), nullable=True),
    sa.Column('avg_salary_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_normalized_title'), ['normalized_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_seniority_level'), ['seniority_level'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('total_job_count', sa.Integer(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('has_pro_access', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('source_ats', sa.String(length=50), nullable=True),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('location_raw', sa.String(length=255), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_is_remote', sa.Boolean(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_min_usd', sa.Integer(), nullable=True),
    sa.Column('salary_max_usd', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_role_id'), ['role_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_title_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_title_variations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_title_variations_original_title'), ['original_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_role_title_variations_role_id'), ['role_id'], unique=False)

    op.create_table('scraper_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('scrape_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('jobs_updated', sa.Integer(), nullable=True),
    sa.Column('jobs_removed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_logs_status'), ['status'], unique=False)

    op.create_table('skills_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('job_count', sa.Integer(), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('company_count', sa.Integer(), nullable=True),
    sa.Column('avg_salary_min', sa.Integer(), nullable=True),
    sa.Column('avg_salary_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'role_id', 'period_date', 'period_type', name='unique_skill_demand_period')
    )
    with op.batch_alter_table('skills_demand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_demand_period_date'), ['period_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_demand_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_demand_skill_id'), ['skill_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_analysis_json', sa.Text(), nullable=True),
    sa.Column('last_analysis_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    op.drop_table('user_skills')
    op.drop_table('user_profiles')
    with op.batch_alter_table('skills_demand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_demand_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skills_demand_role_id'))
        batch_op.drop_index(batch_op.f('ix_skills_demand_period_date'))

    op.drop_table('skills_demand')
    with op.batch_alter_table('scraper_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_logs_status'))
        batch_op.drop_index(batch_op.f('ix_scraper_logs_company_id'))

    op.drop_table('scraper_logs')
    with op.batch_alter_table('role_title_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_title_variations_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_title_variations_original_title'))

    op.drop_table('role_title_variations')
    op.drop_table('payments')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_role_id'))

    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_table('skills')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_seniority_level'))
        batch_op.drop_index(batch_op.f('ix_roles_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_roles_category'))

    op.drop_table('roles')
    op.drop_table('companies')
    # ### end Alembic commands ###
