"""add subcategory to skills

Revision ID: 5a29360164c3
Revises: a3f9c1d2e845
Create Date: 2026-05-31 03:04:14.251837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a29360164c3'
down_revision = 'a3f9c1d2e845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
