"""Add closed_at field to Job model

Revision ID: 9cc0f50d4e52
Revises: ed4a349631e8
Create Date: 2025-12-22 14:56:42.496491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc0f50d4e52'
down_revision = 'ed4a349631e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
