"""Add is_verified to skills

Revision ID: ad16f341a805
Revises: 
Create Date: 2025-12-05 15:05:46.447379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad16f341a805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_companies_ats_type'))
        batch_op.drop_index(batch_op.f('idx_companies_greenhouse_slug'))

    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('job_skills_job_id_skill_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('job_skills_job_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jobs_active'))
        batch_op.drop_index(batch_op.f('idx_jobs_location_city'))
        batch_op.drop_index(batch_op.f('idx_jobs_posted_at'))
        batch_op.drop_index(batch_op.f('idx_jobs_seniority'))
        batch_op.drop_index(batch_op.f('idx_jobs_title'))
        batch_op.drop_constraint(batch_op.f('jobs_source_ats_source_job_id_key'), type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_role_title'))
        batch_op.create_index(batch_op.f('ix_roles_normalized_title'), ['normalized_title'], unique=True)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('aliases',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('user_profiles_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('user_skills_user_id_skill_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_skills_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_skills_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('user_skills_user_id_skill_id_key'), ['user_id', 'skill_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_profiles_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('aliases',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_normalized_title'))
        batch_op.create_index(batch_op.f('uq_role_title'), ['normalized_title'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('jobs_source_ats_source_job_id_key'), ['source_ats', 'source_job_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_jobs_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_seniority'), ['seniority_level'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_posted_at'), [sa.literal_column('posted_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_location_city'), ['location_city'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_active'), ['is_active'], unique=False)

    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('job_skills_job_id_fkey'), 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('job_skills_job_id_skill_id_key'), ['job_id', 'skill_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_companies_greenhouse_slug'), ['greenhouse_slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_companies_ats_type'), ['ats_type'], unique=False)

    # ### end Alembic commands ###
