"""add search_aliases to roles

Revision ID: bc9471b18267
Revises: a1c9e3f82d47
Create Date: 2026-05-10 02:13:45.850193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9471b18267'
down_revision = 'a1c9e3f82d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('auth_tokens_token_hash_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token_hash'))
        batch_op.create_index(batch_op.f('ix_auth_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_skills_dirty'), ['skills_dirty'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_aliases', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('skill_candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('skill_candidates_name_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_skill_candidates_name'))
        batch_op.create_index(batch_op.f('ix_skill_candidates_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_candidates_name'))
        batch_op.create_index(batch_op.f('ix_skill_candidates_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('skill_candidates_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('search_aliases')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_skills_dirty'))

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token_hash'))
        batch_op.create_index(batch_op.f('ix_auth_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('auth_tokens_token_hash_key'), ['token_hash'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
