"""add newsletter_subscribers

Revision ID: d9f4a1c7b2e8
Revises: f2a9c8d41e63
Create Date: 2026-08-07

Blog newsletter subscribers (single opt-in, token-based unsubscribe).
Hand-written (not autogenerated) so it can be authored without a DB connection.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd9f4a1c7b2e8'
down_revision = 'f2a9c8d41e63'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'newsletter_subscribers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('token'),
    )


def downgrade():
    op.drop_table('newsletter_subscribers')
