"""add market_insight_snapshots

Revision ID: e4c1a7f9b21d
Revises: d9f4a1c7b2e8
Create Date: 2026-08-13

Weekly precomputed, validity-gated market insights for the insight-first landing.
Hand-written (not autogenerated) so it can be authored without a DB connection.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4c1a7f9b21d'
down_revision = 'd9f4a1c7b2e8'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'market_insight_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('kind', sa.String(length=32), nullable=False),
        sa.Column('scope', sa.String(length=96), nullable=False, server_default='overall'),
        sa.Column('rank', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('payload', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_market_insight_snapshots_week_start',
                    'market_insight_snapshots', ['week_start'])
    op.create_index('ix_market_insight_week_kind_scope',
                    'market_insight_snapshots', ['week_start', 'kind', 'scope'])


def downgrade():
    op.drop_index('ix_market_insight_week_kind_scope', table_name='market_insight_snapshots')
    op.drop_index('ix_market_insight_snapshots_week_start', table_name='market_insight_snapshots')
    op.drop_table('market_insight_snapshots')
