"""Add industry to companies

Revision ID: ed4a349631e8
Revises: ad16f341a805
Create Date: 2025-12-13 08:12:15.715801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed4a349631e8'
down_revision = 'ad16f341a805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role_insights_role_name'))

    op.drop_table('role_insights')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_skills_durability_tier'))
        batch_op.drop_column('durability_tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durability_tier', sa.VARCHAR(length=20), server_default=sa.text("'evolving'::character varying"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_skills_durability_tier'), ['durability_tier'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('industry')

    op.create_table('role_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('headline', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('whats_growing', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('whats_declining', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('evolved_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('evolved_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_strong', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_moderate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_weak', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"wef_2025": true, "job_postings": true}\'::jsonb'), autoincrement=False, nullable=True),
    sa.Column('jobs_analyzed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('role_insights_pkey')),
    sa.UniqueConstraint('role_name', name=op.f('role_insights_role_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('role_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_role_insights_role_name'), ['role_name'], unique=False)

    # ### end Alembic commands ###
