"""add_unique_source_job_constraint

Revision ID: eebdef0daefa
Revises: d3f8a21c9b05
Create Date: 2026-05-15 06:49:14.945034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebdef0daefa'
down_revision = 'd3f8a21c9b05'
branch_labels = None
depends_on = None


def upgrade():
    # Remove any duplicate (source_ats, source_job_id) pairs, keeping the highest id
    op.execute("""
        DELETE FROM jobs
        WHERE id NOT IN (
            SELECT MAX(id)
            FROM jobs
            GROUP BY source_ats, source_job_id
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_jobs_source_job', ['source_ats', 'source_job_id'])

    with op.batch_alter_table('unmatched_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_candidates_status'))
        batch_op.create_index(batch_op.f('ix_unmatched_titles_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_titles_status'))
        batch_op.create_index(batch_op.f('ix_role_candidates_status'), ['status'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_jobs_source_job', type_='unique')

    # ### end Alembic commands ###
