"""sync_promoted_skills_to_production

Revision ID: fad7f72df7d5
Revises: 057eba6c02d9
Create Date: 2026-05-25 03:30:13.455583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad7f72df7d5'
down_revision = '057eba6c02d9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
INSERT INTO skills (id, name, category, aliases)
    VALUES
        (4710, 'Claude', 'Technical', ARRAY['claude ai','anthropic claude']),
        (4711, 'Claude Code', 'Technical', ARRAY['claude code']),
        (4712, 'Gemini', 'Technical', ARRAY['google gemini','gemini ai']),
        (4713, 'Midjourney', 'Technical', ARRAY['midjourney ai']),
        (4714, 'Amazon Bedrock', 'Technical', ARRAY['aws bedrock','bedrock']),
        (4715, 'AutoGen', 'Technical', ARRAY['autogen']),
        (4716, 'AgentForce', 'Technical', ARRAY['agentforce','salesforce agentforce']),
        (4717, 'Windsurf', 'Technical', ARRAY['windsurf ide']),
        (4718, 'DeepSpeed', 'Technical', ARRAY['deepspeed']),
        (4719, 'ONNX', 'Technical', ARRAY['onnx runtime','open neural network exchange']),
        (4720, 'Delta Lake', 'Technical', ARRAY['delta lake']),
        (4721, 'foundation models', 'Technical', ARRAY['large foundation models']),
        (4722, 'transformer architectures', 'Technical', ARRAY['transformer architecture','transformers']),
        (4723, 'quantization', 'Technical', ARRAY['model quantization','llm quantization']),
        (4724, 'LLMOps', 'Technical', ARRAY['llmops','llm operations']),
        (4725, 'conversational AI', 'Technical', ARRAY['conversational ai','dialogue systems']),
        (4726, 'coding agents', 'Technical', ARRAY['ai coding agents']),
        (4727, 'EC2', 'Technical', ARRAY['aws ec2','amazon ec2']),
        (4728, 'SQS', 'Technical', ARRAY['aws sqs','amazon sqs']),
        (4729, 'AKS', 'Technical', ARRAY['azure kubernetes service']),
        (4730, 'GKE', 'Technical', ARRAY['google kubernetes engine']),
        (4731, 'EKS', 'Technical', ARRAY['amazon eks','elastic kubernetes service']),
        (4732, 'VPN', 'Technical', ARRAY['virtual private network','vpns']),
        (4733, 'VLANs', 'Technical', ARRAY['vlan','virtual local area network']),
        (4734, 'HAProxy', 'Technical', ARRAY['haproxy']),
        (4735, 'Loki', 'Technical', ARRAY['grafana loki']),
        (4736, 'OpenSearch', 'Technical', ARRAY['amazon opensearch','elasticsearch/opensearch']),
        (4737, 'Bicep', 'Technical', ARRAY['azure bicep']),
        (4738, 'policy-as-code', 'Technical', ARRAY['policy as code','open policy agent','opa']),
        (4739, 'GPU infrastructure', 'Technical', ARRAY['gpu cluster','gpu compute']),
        (4740, 'GPU', 'Technical', ARRAY['graphics processing unit','gpus']),
        (4741, 'YAML', 'Technical', ARRAY['yaml configuration']),
        (4742, 'OOP', 'Technical', ARRAY['object-oriented programming','object oriented programming']),
        (4743, 'asyncio', 'Technical', ARRAY['async programming','asynchronous programming','async/await']),
        (4744, 'WebGL', 'Technical', ARRAY['webgl','web graphics']),
        (4745, 'HLSL', 'Technical', ARRAY['high level shading language']),
        (4746, 'ROS', 'Technical', ARRAY['robot operating system','ros2']),
        (4747, 'Webpack', 'Technical', ARRAY['webpack','module bundler']),
        (4748, 'SonarQube', 'Technical', ARRAY['sonarqube']),
        (4749, 'Cucumber', 'Technical', ARRAY['cucumber testing','bdd cucumber']),
        (4750, 'JMeter', 'Technical', ARRAY['apache jmeter']),
        (4751, 'TestRail', 'Technical', ARRAY['testrail']),
        (4752, 'TeamCity', 'Technical', ARRAY['teamcity']),
        (4753, 'Harness', 'Technical', ARRAY['harness ci/cd','harness platform']),
        (4754, 'Yocto', 'Technical', ARRAY['yocto project','yocto linux']),
        (4755, 'configuration management', 'Technical', ARRAY['config management','configuration mgmt']),
        (4756, 'performance tuning', 'Technical', ARRAY['perf tuning','query tuning','performance optimization']),
        (4757, 'backend development', 'Technical', ARRAY['backend engineering','server-side development']),
        (4758, 'frontend architecture', 'Technical', ARRAY['front-end architecture','frontend build systems']),
        (4759, 'signal integrity', 'Technical', ARRAY['si analysis','signal integrity analysis']),
        (4760, 'RTL design', 'Technical', ARRAY['register transfer level','rtl']),
        (4761, 'Static Timing Analysis', 'Technical', ARRAY['sta','timing analysis']),
        (4762, 'timing closure', 'Technical', ARRAY['timing closure']),
        (4763, 'post-silicon validation', 'Technical', ARRAY['silicon validation','post-silicon debug']),
        (4764, 'hardware bring-up', 'Technical', ARRAY['hw bring-up','board bring-up']),
        (4765, 'design of experiments', 'Technical', ARRAY['doe','experiment design']),
        (4766, 'design for test', 'Technical', ARRAY['dft','design for testability']),
        (4767, 'model-based design', 'Technical', ARRAY['mbd','model based design']),
        (4768, 'energy modeling', 'Technical', ARRAY['building energy modeling','thermal modeling']),
        (4769, 'PCIe', 'Technical', ARRAY['pci express','pcie']),
        (4770, 'RISC-V', 'Technical', ARRAY['risc v','riscv']),
        (4771, 'VHDL', 'Technical', ARRAY['vhdl design']),
        (4772, 'SPI', 'Technical', ARRAY['serial peripheral interface']),
        (4773, 'I2C', 'Technical', ARRAY['i2c protocol','inter-integrated circuit']),
        (4774, 'UART', 'Technical', ARRAY['universal asynchronous receiver transmitter']),
        (4775, 'JTAG', 'Technical', ARRAY['jtag debugging']),
        (4776, 'OIDC', 'Technical', ARRAY['openid connect']),
        (4777, 'SIP', 'Technical', ARRAY['session initiation protocol']),
        (4778, 'VoIP', 'Technical', ARRAY['voice over ip','voip systems']),
        (4779, 'SFTP', 'Technical', ARRAY['secure file transfer protocol']),
        (4780, 'IPsec', 'Technical', ARRAY['ipsec vpn','ip security']),
        (4781, 'RFID', 'Technical', ARRAY['rfid technology','radio frequency identification']),
        (4782, 'GPS', 'Technical', ARRAY['global positioning system','gps systems']),
        (4783, 'PLC', 'Technical', ARRAY['programmable logic controller','plc programming','plc systems']),
        (4784, 'CMMS', 'Technical', ARRAY['computerized maintenance management system','cmms systems']),
        (4785, 'VFDs', 'Technical', ARRAY['variable frequency drives','vfd','variable speed drives']),
        (4786, 'dSPACE', 'Technical', ARRAY['dspace']),
        (4787, 'cryogenic systems', 'Technical', ARRAY['cryogenics','cryogenic engineering']),
        (4788, 'photogrammetry', 'Technical', ARRAY['photogrammetric analysis']),
        (4789, 'CAD/CAM software', 'Technical', ARRAY['cad cam','cam software']),
        (4790, 'RF design', 'Technical', ARRAY['rf engineering','radio frequency design']),
        (4791, 'radar systems', 'Technical', ARRAY['radar engineering']),
        (4792, 'PCBA', 'Technical', ARRAY['printed circuit board assembly','pcb assembly']),
        (4793, 'micrometers', 'Technical', ARRAY['micrometer','precision measurement tools']),
        (4794, 'calipers', 'Technical', ARRAY['vernier calipers','precision calipers']),
        (4795, 'Geometric Dimensioning', 'Technical', ARRAY['gd&t','geometric dimensioning and tolerancing']),
        (4796, 'electrical codes', 'Technical', ARRAY['nec','national electrical code','electrical standards']),
        (4797, 'SAP', 'Technical', ARRAY['sap erp','sap hana','sap s/4hana','sap systems']),
        (4798, 'VMware', 'Technical', ARRAY['vmware vsphere','vmware esxi']),
        (4799, 'Procore', 'Technical', ARRAY['procore platform']),
        (4800, 'Bluebeam', 'Technical', ARRAY['bluebeam revu']),
        (4801, 'Yardi', 'Technical', ARRAY['yardi voyager','yardi systems']),
        (4802, 'Civil 3D', 'Technical', ARRAY['autocad civil 3d','autodesk civil 3d']),
        (4803, 'Teamcenter', 'Technical', ARRAY['siemens teamcenter']),
        (4804, 'Primavera P6', 'Technical', ARRAY['oracle primavera','p6 scheduling']),
        (4805, 'Bloomberg', 'Technical', ARRAY['bloomberg terminal','bloomberg data']),
        (4806, 'FactSet', 'Technical', ARRAY['factset platform']),
        (4807, 'Klaviyo', 'Technical', ARRAY['klaviyo email']),
        (4808, 'Stripe', 'Technical', ARRAY['stripe payments','stripe api']),
        (4809, 'Twilio', 'Technical', ARRAY['twilio api','twilio communications']),
        (4810, 'Zscaler', 'Technical', ARRAY['zscaler zia','zscaler zero trust']),
        (4811, 'Wiz', 'Technical', ARRAY['wiz cloud security']),
        (4812, 'Fortinet', 'Technical', ARRAY['fortigate','fortinet firewall']),
        (4813, 'HiBob', 'Technical', ARRAY['hibob hris']),
        (4814, 'Navan', 'Technical', ARRAY['navan travel']),
        (4815, 'Bill.com', 'Technical', ARRAY['bill.com payments']),
        (4816, 'Xero', 'Technical', ARRAY['xero accounting']),
        (4817, 'Avalara', 'Technical', ARRAY['avalara tax']),
        (4818, 'Zip', 'Technical', ARRAY['zip procurement']),
        (4819, 'Veeva', 'Technical', ARRAY['veeva vault','veeva crm','veeva systems']),
        (4820, 'CTMS', 'Technical', ARRAY['clinical trial management system']),
        (4821, 'LIMS', 'Technical', ARRAY['laboratory information management system']),
        (4822, 'Workfront', 'Technical', ARRAY['adobe workfront']),
        (4823, 'Cvent', 'Technical', ARRAY['cvent events']),
        (4824, 'Framer', 'Technical', ARRAY['framer design']),
        (4825, 'CapCut', 'Technical', ARRAY['capcut video']),
        (4826, 'Sprout Social', 'Technical', ARRAY['sprout social media']),
        (4827, 'Ahrefs', 'Technical', ARRAY['ahrefs seo']),
        (4828, 'Brandwatch', 'Technical', ARRAY['brandwatch analytics']),
        (4829, 'Meta Ads Manager', 'Technical', ARRAY['facebook ads manager','meta business suite']),
        (4830, 'Optimizely', 'Technical', ARRAY['optimizely experimentation']),
        (4831, 'Pendo', 'Technical', ARRAY['pendo analytics']),
        (4832, 'DOMO', 'Technical', ARRAY['domo bi','domo analytics']),
        (4833, 'Adaptive Insights', 'Technical', ARRAY['workday adaptive insights']),
        (4834, 'Adobe Creative Cloud', 'Technical', ARRAY['adobe cc','creative cloud']),
        (4835, 'Adobe InDesign', 'Technical', ARRAY['indesign']),
        (4836, 'Google Docs', 'Technical', ARRAY['google docs','google workspace docs']),
        (4837, 'Google Slides', 'Technical', ARRAY['google slides','google workspace slides']),
        (4838, 'SOQL', 'Technical', ARRAY['salesforce object query language']),
        (4839, 'Visualforce', 'Technical', ARRAY['salesforce visualforce']),
        (4840, 'Esri ArcGIS', 'Technical', ARRAY['arcgis pro','arcgis esri']),
        (4841, 'IDA Pro', 'Technical', ARRAY['ida pro disassembler','ida debugger']),
        (4842, 'SOAR platforms', 'Technical', ARRAY['security orchestration automation response','soar']),
        (4843, 'threat hunting', 'Technical', ARRAY['cyber threat hunting']),
        (4844, 'DevSecOps', 'Technical', ARRAY['dev sec ops','devsecops pipelines']),
        (4845, 'GRC', 'Technical', ARRAY['governance risk compliance','grc platforms']),
        (4846, 'AML', 'Domain', ARRAY['anti-money laundering','aml compliance']),
        (4847, 'FINRA', 'Domain', ARRAY['finra regulations','financial industry regulatory authority']),
        (4848, 'SLAs', 'Domain', ARRAY['service level agreements','sla management']),
        (4849, 'SOPs', 'Domain', ARRAY['standard operating procedures']),
        (4850, 'PMO', 'Domain', ARRAY['project management office']),
        (4851, 'OKR', 'Domain', ARRAY['objectives and key results','okrs']),
        (4852, 'MarTech', 'Domain', ARRAY['marketing technology','martech stack']),
        (4853, 'paid social', 'Domain', ARRAY['paid social media','social advertising']),
        (4854, 'performance advertising', 'Domain', ARRAY['performance marketing','growth advertising']),
        (4855, 'audience segmentation', 'Domain', ARRAY['customer segmentation','audience targeting']),
        (4856, 'social listening', 'Domain', ARRAY['social media monitoring','brand monitoring']),
        (4857, 'customer data platforms', 'Domain', ARRAY['cdp','cdps','customer data platform']),
        (4858, 'deal desk', 'Domain', ARRAY['deal desk operations']),
        (4859, 'target account selling', 'Domain', ARRAY['tas','account-based selling']),
        (4860, 'strategic account planning', 'Domain', ARRAY['account planning','key account management']),
        (4861, 'product operations', 'Domain', ARRAY['prod ops','product ops']),
        (4862, 'solutions engineering', 'Domain', ARRAY['solutions engineer','presales engineering']),
        (4863, 'revenue cycle management', 'Domain', ARRAY['rcm','revenue cycle']),
        (4864, 'compensation strategy', 'Domain', ARRAY['compensation planning','total rewards strategy']),
        (4865, 'compensation analysis', 'Domain', ARRAY['comp analysis','compensation benchmarking']),
        (4866, 'full-cycle recruiting', 'Domain', ARRAY['end-to-end recruiting','full cycle recruitment']),
        (4867, 'value engineering', 'Domain', ARRAY['ve process','value analysis']),
        (4868, 'semantic modeling', 'Domain', ARRAY['semantic data model','ontology modeling']),
        (4869, 'process safety management', 'Domain', ARRAY['psm','process safety']),
        (4870, 'pharmacovigilance', 'Domain', ARRAY['drug safety','pv','adverse event reporting']),
        (4871, 'GMP', 'Domain', ARRAY['good manufacturing practice','gmp compliance']),
        (4872, 'cGMP', 'Domain', ARRAY['current good manufacturing practice','cgmp regulations']),
        (4873, 'GxP', 'Domain', ARRAY['gxp compliance','gxp regulations']),
        (4874, 'GLP', 'Domain', ARRAY['good laboratory practice']),
        (4875, 'ICH', 'Domain', ARRAY['ich guidelines','ich-gcp','ich gcp']),
        (4876, 'HL7', 'Domain', ARRAY['health level 7','hl7 fhir','fhir']),
        (4877, 'MedDRA', 'Domain', ARRAY['medical dictionary for regulatory activities']),
        (4878, 'CDISC standards', 'Domain', ARRAY['cdisc','sdtm','adam']),
        (4879, '21 CFR Part 11', 'Domain', ARRAY['cfr part 11','21 cfr part 11']),
        (4880, 'value-based care', 'Domain', ARRAY['value based care models','vbc']),
        (4881, 'molecular cloning', 'Domain', ARRAY['gene cloning','recombinant dna']),
        (4882, 'mammalian cell culture', 'Domain', ARRAY['cell culture','mammalian cells']),
        (4883, 'clinical trial operations', 'Domain', ARRAY['clinical operations','cto']),
        (4884, 'regulatory submissions', 'Domain', ARRAY['regulatory filings','nda submissions','inda']),
        (4885, 'design controls', 'Domain', ARRAY['medical device design controls','iso 13485']),
        (4886, 'ISO', 'Domain', ARRAY['iso standards','iso certification']),
        (4887, 'ASME', 'Domain', ARRAY['american society of mechanical engineers','asme standards']),
        (4888, 'IATF', 'Domain', ARRAY['iatf 16949','automotive quality standard']),
        (4889, 'IPC standards', 'Domain', ARRAY['ipc-a-610','ipc electronics standards']),
        (4890, 'PFMEA', 'Domain', ARRAY['process failure mode effects analysis','fmea']),
        (4891, 'FISMA', 'Domain', ARRAY['federal information security management act']),
        (4892, 'NISPOM', 'Domain', ARRAY['national industrial security program']),
        (4893, 'DFARS', 'Domain', ARRAY['defense federal acquisition regulation supplement']),
        (4894, 'EHS', 'Domain', ARRAY['environmental health and safety','ehs management']),
        (4895, 'DORA metrics', 'Domain', ARRAY['dora','deployment frequency','change failure rate']),
        (4896, 'MEP', 'Domain', ARRAY['mechanical electrical plumbing','mep systems']),
        (4897, 'SPC', 'Domain', ARRAY['statistical process control']),
        (4898, 'MES', 'Domain', ARRAY['manufacturing execution system','mes systems']),
        (4899, 'commissioning', 'Domain', ARRAY['building commissioning','system commissioning'])
    ON CONFLICT (id) DO NOTHING;
SELECT setval('skills_id_seq', GREATEST(nextval('skills_id_seq'), 4900) - 1);    """)


def downgrade():
    op.execute("DELETE FROM skills WHERE id >= 4710 AND id <= 4899")
